### ISSUE TITLE
Version in CC about page and in applications list on Windows are different

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#1007]
We need same version of product everywhere.
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/914899e2-2588-44a2-8a6d-3a45e0966985)

**Comment by amangeldizhusubaliev** [comment]
If we *update* CC, old version remains in Control Panel. But if we uninstall it completely and install latest version from getting-started page, latest version will be in Control Panel. 
Should update installer or remove the version of CC from Control Panel.

**Comment by kurmanbekova6** [comment]
Fixed on Master
![screenshot_4](https://user-images.githubusercontent.com/9501291/42488177-1f7e3660-8426-11e8-8054-22420b8d40e5.png)
![screenshot_5](https://user-images.githubusercontent.com/9501291/42488178-1fa22250-8426-11e8-9be2-507a9ce0ab81.png)

**Comment by ibragim13kz** [comment]
Fixed in Prod.
