### ISSUE TITLE
During ssh key deployment progress bar doesn't show any progress

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#1008]
Happens on all OS's: MAC, Windows, Linux.

## Expected Behavior
It should move closer to 100% percent
## Current Behavior
Now it is stopping on 1% and after some time env became under_modification

## Steps to Reproduce
1. Open ssh-key management form in CC
2. Select env
3. Push "deploy key" button
Result progress bar stuck on 1%
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/5e5661fd-7ee2-4db4-8164-2956fb1bd778)

**Comment by TerGunter** [comment]
fixed on master

**Comment by TerGunter** [comment]
fixed on master

**Comment by amangeldizhusubaliev** [comment]
fixed on prod.
