### ISSUE TITLE
SSH- key management isn't user friendly

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#1023]
Current situation:
If user has a lot of envs (more than 1), and he/she wants to deploy his ssh key to env, then the user must mark check box that is opposite to the env. And If later user needs to deploy key to other env. he/she should add mark to checkbox of next env. 
But As I understand if my key deployed to first env, I need to uncheck its checkbox, but if I will make this key will be deleted from first env. 
We need to add some buttons for deploy and delete keys from each env,  more general because each user can understand differently (like me)
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/a5000991-283f-44dd-bc1a-5aaef99bf3ce)

**Comment by Almansherov** [comment]
Gotta get instructions from Scott on this issue

**Comment by Almansherov** [comment]
Fixed by this issue: https://github.com/subutai-io/control-center/issues/1446
