### ISSUE TITLE
Wrong message by CC after peer's registration

### ISSUE THREAD

**Issue by TerGunter** [subutai-io/control-center#1024]
After peer's registration to bazaar CC shows me error
![Screen Shot 2018-05-26 at 12.44.21 PM.png](https://images.zenhubusercontent.com/5ad825df4b5806bc2bcfb9d1/42d14ebd-d1b0-4512-b050-46b206ebbb19)
Everything is fine, just wrong message, cuz peer's registration was successfully

**Comment by amangeldizhusubaliev** [comment]
fixed on master.

**Comment by amangeldizhusubaliev** [comment]
fixed on prod.
