### ISSUE TITLE
Ease Uninstalling Process

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1040]
Uninstalling process is complicated. 
## Expected Behavior

In order to uninstall the Control Center or its components there should be 'Uninstall' buttons next to each component in *About*. Also there should be two buttons in the bottom of *About* section 'Install all' and 'Uninstall all'. 
## Current Behavior

Right now there is no any buttons there and user has to delete CC through the command line.

**Comment by Erkin97** [comment]
I think better to rework About Dialog and after that to add this functionality

**Comment by ibragim13kz** [comment]
Done in Master.

**Comment by ibragim13kz** [comment]
Done in Production.
