### ISSUE TITLE
Show error messages in terminal when peer creation fails

### ISSUE THREAD

**Issue by Erkin97** [subutai-io/control-center#1041]
## Expected Behavior
Show error messages on terminal

## Current Behavior
In terminal no error messages, however CC says it has error messages

## Possible Solution
In the end peer creation show output of error file and make "Press Enter to finish installation", so user user can read before closes

## Steps to Reproduce
1. Create peer
2. While peer creation, press Destroy when Peer status is PoweOFF or Not Ready

## Context (Environment)
All OS

**Comment by Erkin97** [comment]
![image](https://user-images.githubusercontent.com/22586805/40648226-b6620004-634f-11e8-8d7a-8565aeeb45d1.png)
it will look like this on MacOS

**Comment by TerGunter** [comment]
![image](https://user-images.githubusercontent.com/38347277/40657384-7bda56b0-6369-11e8-9e9b-0224ce38cce3.png)
Win10

**Comment by ibragim13kz** [comment]
Done in Master.

**Comment by amangeldizhusubaliev** [comment]
fixed on prod.
