### ISSUE TITLE
User warning about the time needed for PeerOS to load management

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1047]
## Expected Behavior

Right after how Vagrant is done with peer creation process, there should be a message telling that it takes time to load management. Only after that user can enter Subutai Console using the peer parameters. 
## Current Behavior

Vagrant says that everything is completed, but actually not yet. 
## Possible Solution

We can just add message telling user that it will take some time and this is not a big deal. 
## Steps to Reproduce

1. Start peer creation process through Control Center
2. Vagrant will notify user about the completion of the process
3. Try to enter Subutai Console using the parameters of the peer
4. And here you fail, because PeerOS needs time to load management

**Comment by amangeldizhusubaliev** [comment]
fixed on master.

**Comment by amangeldizhusubaliev** [comment]
fixed on prod.
