### ISSUE TITLE
"Destroy" button in the peer registered to bazaar

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1048]
If a peer is registered to bazaar, there is "Destroy" button disabled. It may confuse a user, if there would not be an explanation for that. 
## Expected Behavior

There should be toolbar (or appearing tooltip) that explains the reason for disabled function and shows how to get to the point where user can destroy his/her peer. 
## Current Behavior

Due to the fingerprint, peers registered to bazaar don't have a function to be destroyed by user through Control Center and user don't know how to destroy it. 
## Possible Solution

Appearing toolbar can solve this problem by explaining user how to behave in order to accomplish that.

**Comment by ibragim13kz** [comment]
Done in Master.

**Comment by amangeldizhusubaliev** [comment]
fixed on prod.
![f](https://user-images.githubusercontent.com/38368928/40782377-e1f14f7e-6500-11e8-83bf-71883b73dcc8.png)
