### ISSUE TITLE
The lack of feedback not knowing either the peer is still being built or not

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1051]
## Expected Behavior

User should be aware how long he/she should wait in order the peer to be finished. 
## Current Behavior

User just does not see and not aware either the peer is still being built or not.
## Possible Solution

You can give a progress bar to inform the user about how far the peer is in building. This can be done easily by using some events logged by the vagrant boxes which can be used by the vagrant plugin and exposed to CC. The provisioning scripts can push text events to a file. This can be picked up by the plugin and made available to CC.

## Quote from Slack

"People complaining about having proper feedback not knowing when the peer building is done and shit.

You can give a progress bar to inform the user about how far the peer is in building. This can be done easily by using some events logged by the vagrant boxes which can be used by the vagrant plugin and exposed to CC. The provisioning scripts can push text events to a file. This can be picked up by the plugin and made available to CC.

If y'all need a solid architecture for that call me. Also you can enable a tty console on the VM and just read the output of it like from a serial device."  -- (c) Alex

**Comment by crioto** [comment]
#1074

**Comment by Erkin97** [comment]
duplicate #1074
