### ISSUE TITLE
"Eye Icon" in Registering Peer, Peer Creation, and Login windows

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1066]
## Expected Behavior

Users should be able to see their passwords in 'Login' and 'Peer Creation' windows. 
## Current Behavior

Well, obviously they cannot do that, yet. 
## Possible Solution

We can put an "eye" icon so that if a user presses it, she/he would be able to see the input. 

Suggestions: 

![login](https://user-images.githubusercontent.com/32430693/41140326-9c81eb9c-6b0e-11e8-9e7a-912427c273f0.png)
![create peer](https://user-images.githubusercontent.com/32430693/41140329-a5069182-6b0e-11e8-9bdf-881cfe4c17d7.png)

**Comment by satarovaAziza** [comment]
fixed on master.

**Comment by ibragim13kz** [comment]
Done in Prod.
