### ISSUE TITLE
Section `About` can be confusing for a user

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1072]
Do we have to rename `About` section in Control Center? Because many products have only information or history in `About`. 

Each component in `About` should give description. User has to understand what are they for and that they do not hurt a machine. 
## Expected Behavior

The section where user installs the components should be constructive and clear. 
The components can have either toolbars with information or hyperlinks to the official websites of the components.
## Current Behavior

`About` has the list of components without information.

Feel free to share ideas if you have any.

Suggestion:

![about](https://user-images.githubusercontent.com/32430693/41147307-dfcce262-6b27-11e8-818e-bcfc46cb500b.png)

**Comment by akarasulu** [comment]
I was thinking of having tabs on this dialog. The first tab is some simple information that traditional About dialogs have.  Just look at how Apple does it with it's About screen. As you can see, you can drill deeper if you like after the simple screen that summarizes the machine information on Mac OS.

![screen shot 2018-05-30 at 8 27 52 pm](https://user-images.githubusercontent.com/10051386/40785134-8244f8ec-6509-11e8-878a-bcf174555138.png)

So you get the basics. If you want to see more detailed information then you have to select a tab. Scott should review this and decide but I'm just giving my copycat thoughts here. I think we can have an Installed, and Available software tab for the things that are and are **NOT** installed. Or we can organize tabs based on software and resources like:

* Subutai Components
  * E2E
  * P2P
  * CC
* Providers and Hypervisors
  * Vagrant
  * Vagrant Boxes
  * Vagrant Plugins
  * Hypervisors
* Client Software
  * X2GO
  * Chrome

**Comment by akarasulu** [comment]
BTW in the overview we can have some analytic information after running basic diagnostics about what hypervisor is available and how much RAM/CPU/DISK should be deemed usable by peers on this system. @crioto wrote a lot of code like this for the launcher project a year ago. The project is in the [Subutai Attic](https://github.com/subutai-attic/launcher) right now.

**Comment by ux-scott** [comment]
The concern I have with burying things behind tabs is that we'd need to have some means of notifying users if they need to take manual steps to update components. It's fine for just displaying current status (what you've shown for Mac) but not so good for installation and updates and that sort of interaction.

**Comment by ibragim13kz** [comment]
Done in Master.

**Comment by ibragim13kz** [comment]
Done in Prod.
