### ISSUE TITLE
Progress Bar is Needed When a Peer is Being Created

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1074]
User should know that the process is being completed and he/she has to just wait for a while.
## Expected Behavior

There should be a bar or message with estimation time in order to keep user updated.
## Current Behavior

After pressing the button `create`, user has to wait for 10-15 seconds without knowing that everything is fine.

**Comment by ux-scott** [comment]
This is a general problem throughout CC - lack of feedback, delays when user thinks something might be broken.

**Comment by Erkin97** [comment]
* Need packet to write logs inside of .vagrant folder
[link to the issue in packer](https://github.com/subutai-io/packer/issues/79)

**Comment by kurmanbekova6** [comment]
Fixed on Master

**Comment by ibragim13kz** [comment]
Done in Production.
