### ISSUE TITLE
The Difference between Console Peers and Local Peers information in Peer Creation Window

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1075]
## Expected Behavior

User should know what is the difference between the types of peers and be able to understand what password she/he should put. Otherwise, it confuses users.
## Current Behavior

When user puts information about peer, there is no any hints about the types of peers.

**Comment by ibragim13kz** [comment]
Done in Master.

**Comment by ibragim13kz** [comment]
Done in Prod.
