### ISSUE TITLE
Peer Creation data paid or free, private or public

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1076]
## Expected Behavior

User should be able to put information about peer while creating it. Paid or free and if paid then the price. Private or public
## Current Behavior

it is possible to do it only through bazaar.

**Comment by Erkin97** [comment]
* Waiting bazzar to implement rest api
[link to the issue in bazaar](https://github.com/optdyn/hub/issues/5978)

**Comment by Erkin97** [comment]
This issues requires big ui/ux changes in CC, so it's better to change CC ui/ux first before implementing this issue

**Comment by Almansherov** [comment]
This feature requires REST apis and it is too complicated due to lack of time resources
