### ISSUE TITLE
Wrong state value of peer when it starts to build on Mac

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1081]
When a user creates peer through Control Center, Peer state shows error message "Peer is broken" while PeerOS is being built. 
## Expected Behavior

CC should aware user that PeerOS is being built and it takes some time. 
## Current Behavior

`Peer is broken` means that Peer is not gonna work anymore and it will lead to the misunderstanding.

<img width="628" alt="screen shot 2018-05-31 at 2 42 55 pm" src="https://user-images.githubusercontent.com/32430693/40779033-3e7ce55c-64f5-11e8-9cf6-6c45635ec7e7.png">

**Comment by amangeldizhusubaliev** [comment]
Didn't face this problem
![screen shot 2018-06-18 at 6 50 48 pm](https://user-images.githubusercontent.com/38368928/41536921-c8c866f0-7328-11e8-893f-1664e59fcb8c.png)

**Comment by amangeldizhusubaliev** [comment]
Need to reproduce on Mac.

**Comment by Erkin97** [comment]
it has been fixed

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Done in Prod.
