### ISSUE TITLE
CC checks a machine's configurations right after click to `create peer` button

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1082]
Checking all machine configuration when user presses `create peer`. 
## Expected Behavior

User will be able to see the following processes after pressing `create peer` button:
CC checks vagrant plugins for update
CC checks vb and vagrant state
CC checks file directory
## Current Behavior

Now user does not have possibilities to see the machine's configurations.

**Comment by Almansherov** [comment]
Fixed on Master

**Comment by ibragim13kz** [comment]
Done in Prod.
