### ISSUE TITLE
CC login window when bazaar is unreachable

### ISSUE THREAD

**Issue by amangeldizhusubaliev** [subutai-io/control-center#1083]
When bazaar is unreachable (master or prod, depending on version of CC), this error appears. I am sure that mail and password are correct. ![Screenshot from 2018-05-31 18-10-39.png](https://images.zenhubusercontent.com/5ad825c34b5806bc2bcfb9cb/827254f1-c581-47ad-a670-f8ef54191e7c)
CC should show something like `bazaar.subutai.io is unreachable`, if it is so.

**Comment by kurmanbekova6** [comment]
Fixed in master
![screenshot from 2018-06-07 14-42-44](https://user-images.githubusercontent.com/9501291/41155421-c094f354-6b3f-11e8-867c-79805fbfee90.png)

**Comment by ibragim13kz** [comment]
Fixed in Prod.
