### ISSUE TITLE
CC crashed

### ISSUE THREAD

**Issue by TerGunter** [subutai-io/control-center#1084]
CC crashed if you try to register/unregister peer and after pressing button need to close window and repeat again

**Comment by amangeldizhusubaliev** [comment]
![ssssssssssssss](https://user-images.githubusercontent.com/38368928/40821359-2e75a5fc-6588-11e8-84c4-6349cc82224d.png)

**Comment by amangeldizhusubaliev** [comment]
No need to press register/unregister twice. CC crashes if we do the following steps:
0) need to have peer on this machine, registered/unregistered doesn't matter.
1) go to peers menu press register/unregister. 
2) new dialog window appears, here press register/unregister again.
3) close this dialog window by pressing exit (x) button.
4) wait 5-10 seconds, CC crashes.
Reproduced this on Windows 10 and Ubuntu 18.04.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
