### ISSUE TITLE
Control Center crashes after machine goes into the sleep mode on Mac

### ISSUE THREAD

**Issue by ibragim13kz** [subutai-io/control-center#1086]
I just left the machine to sleep for 1.5 hour, so when I turned it on, CC was already closed.

**Comment by ibragim13kz** [comment]
[logs_16.txt](https://github.com/subutai-io/control-center/files/2061913/logs_16.txt)
[logs_17.txt](https://github.com/subutai-io/control-center/files/2061915/logs_17.txt)
[logs_18.txt](https://github.com/subutai-io/control-center/files/2061916/logs_18.txt)

**Comment by amangeldizhusubaliev** [comment]
Need to check if auto log out is turned on, may be a cause. 
System Preferences -> Security & Privacy -> Advanced...
Make sure that "Log out after ... minutes of inactivity" is unchecked.

**Comment by kurmanbekova6** [comment]
After sleeping mode, CC was closed itself.
[logs_18.txt](https://github.com/subutai-io/control-center/files/2169106/logs_18.txt)
[logs_17.txt](https://github.com/subutai-io/control-center/files/2169107/logs_17.txt)

**Comment by amangeldizhusubaliev** [comment]
Cause of this crash: CC creates too much new threads. MacOS allows creating only 2048 new threads per process. CC used to start a new thread every 5 seconds for checking P2Ps, Peers' statuses. Related issue: #1445.

**Comment by Almansherov** [comment]
Have not faced this issue. 
Has left cc on windows and on debian machines

**Comment by Almansherov** [comment]
Has left MacOS in sleep mode.
All of my envrionments are healthy and possible to check:

<img width="371" alt="screen shot 2018-10-31 at 11 36 20 am" src="https://user-images.githubusercontent.com/32430693/47768206-36450980-dd01-11e8-85aa-57ce4e0f6615.png">

Fixed in prod
