### ISSUE TITLE
Warning About Components' Versions

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1100]
## Expected Behavior

'About' section should inform a user about the versions of the components so that they could be updated as soon as the new versions needed. 
## Current Behavior

There is a list of components and there is no informing feature.
## Possible Solution

It is possible to make a little sign near to each component that appears in case if user has to update something.
## Steps to Reproduce

1. Open Control Center
2. And 'About' section
3.
4.

**Comment by ibragim13kz** [comment]
@Almansherov @Erkin97 @amangeldizhusubaliev We can consider this issue as completed only after X2Go version will be added.

**Comment by Almansherov** [comment]
@ibragim13kz X2Go client gets all the logs into STDERR as error messages and if CC requests for version, it opens GUI

**Comment by ibragim13kz** [comment]
Done in Prod.
