### ISSUE TITLE
On Mac OS when user pushes Environments button, CC closes the window

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#1104]
## Expected Behavior
When user pushes `environments` button, window should be opened 

## Current Behavior
When user pushes `environments` button, window closes

![image](https://user-images.githubusercontent.com/34295807/41030944-4ae924b2-69a1-11e8-81e1-a8b4ecec4dab.png)

**Comment by amangeldizhusubaliev** [comment]
Mac specific function. It closes not only CC, it closes all the tray apps' menus, if we click on unclickable elements. 
![screen shot 2018-06-19 at 3 28 34 pm](https://user-images.githubusercontent.com/38368928/41589161-96e1151c-73d5-11e8-9ef3-c436ab2f2cc8.png)
For example, if we click on "Start" option (it is disabled), menu closes. On Ubuntu, same application's 
tray menu will not close if we click disabled "Start" option there too.

**Comment by ibragim13kz** [comment]
Failed in Master.
