### ISSUE TITLE
Reduce the vertical size of 'Settings' screen 

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1114]
There are empty spaces on the top and bottom of the screen. It would be way better to reduce them
## Expected Behavior
The window should not take too much space

![44444444444](https://user-images.githubusercontent.com/32430693/41096848-b9038416-6a77-11e8-9772-5275771988a5.png)

**Comment by ibragim13kz** [comment]
Fixed in master

**Comment by ibragim13kz** [comment]
Done in Prod,
