### ISSUE TITLE
Icon in menu invisible 

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#1115]
It is better to make it lighter because it isn't comfortable to see it right now:
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/2ef42762-e70c-4813-b7f9-d5bb95e5fbb2)

**Comment by ibragim13kz** [comment]
Done in Master.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
