### ISSUE TITLE
CC doesn't show my existing environments (master)

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#1116]
OS Windows 10.
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/ca9607c3-aec5-4b98-9696-62de2e5b6bb6)

**Comment by AlinaPenkina** [comment]
[logs.txt](https://github.com/subutai-io/control-center/files/2082841/logs.txt)

**Comment by Erkin97** [comment]
* bazaar couldn't process rest request from CC
```[09:00:05] [..\hub\src\RestWorker.cpp(771)] Critical: Send request network error : Error transferring https://masterbazaar.subutai.io/rest/v1/tray/environments - server replied: Server Error ```
```[09:00:05] [..\hub\src\HubController.cpp(179)] Critical: Refresh environments failed. Err_code : 6, Net_err : 401 ```

**Comment by AlinaPenkina** [comment]
this is bazaars problem #5903
