### ISSUE TITLE
Make tray menu skins

### ISSUE THREAD

**Issue by Lezh1k** [subutai-io/control-center#112]
Tray menu should use skins, color schemes etc. Not only menu, but every component there. 
So we should provide that mechanism. Users like it :)

**Comment by amol4anoff** [comment]
I see gray(default), black and orange-black.

**Comment by amol4anoff** [comment]
One moment - i changed skin to dark, but main tray menu remains gray, why?

<img width="1228" alt="screen shot 2018-02-14 at 7 04 28 pm" src="https://user-images.githubusercontent.com/33647491/36205762-07246834-11ba-11e8-8240-dcb43dedf766.png">

**Comment by amol4anoff** [comment]
One more thing - i change skin from gray to dark, re-launch tray and see that it is gray. But when i check settings, i see that dark skin is selected there.

**Comment by crioto** [comment]
Done
