### ISSUE TITLE
P2P looks like more status bar than command

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1121]
The first item in menu (p2p) does not look like command. There are 'Stop' and 'Start' buttons inside.

As one of the possible decisions, we can  reduce the separate window for p2p and put one button near to p2p status text.

*P2P is running --> Stop*
*P2P is not running --> Start*

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
