### ISSUE TITLE
'My Peers' window's restructuring 

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1122]
Due to the complexity of Peer details, there is a suggestion to combine some functions and make the window ordered and proper.

It would look like this:
 

![my peers](https://user-images.githubusercontent.com/32430693/41147907-6c261502-6b29-11e8-9637-b4460fecc93e.png)

**Comment by ibragim13kz** [comment]
Done in Master.

**Comment by ibragim13kz** [comment]
Done in Prod.
