### ISSUE TITLE
Edit the error messages from revised document

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1123]
The Control Center messages was revised. We have to replay the existing once with the new messages.

**Comment by AlinaPenkina** [comment]
This message shouldn't be here;
![image](https://user-images.githubusercontent.com/34295807/41279926-8ac87d5a-6e4f-11e8-8fa7-ca4bb0f5b602.png)

**Comment by ibragim13kz** [comment]
Closing. We'll reopen if we'll face some wrong messages.
