### ISSUE TITLE
CC doesn't show any message about incorrectness of Peer names.

### ISSUE THREAD

**Issue by satarovaAziza** [subutai-io/control-center#1124]
When we register peer on control center, the name cannot contain symbols, spaces, and it cannot be empty. Control Center does not remind the user about that except empty.![Cannotreg.png](https://images.zenhubusercontent.com/5b0e5b9dc7faeb213bec8766/df0c4c0a-796f-4675-bd08-dff1177d6df0)![cannotregempty.png](https://images.zenhubusercontent.com/5b0e5b9dc7faeb213bec8766/0479925e-0ed0-4e7d-b24c-67bc29be032a)

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
