### ISSUE TITLE
After ssh-key deployment CC doesn't see that key is existing in environment

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#1143]
After ssh-key deployment CC doesn't see that key is existing in environment. That is why user can't connect by ssh with container.
Windows 10.
It happens because windows adds ```/r``` ii the end of ssh-key.

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Didn't face it in Production.
