### ISSUE TITLE
Progress bar is needed on Vagrant  installation

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1157]
User should know that the process of installation either going fine or not and if not, there should be user actions. 
## Expected Behavior

Progress bar of an installation.
## Current Behavior

It takes some time after installation and user may get confused.

**Comment by ibragim13kz** [comment]
Done in Master.

**Comment by ibragim13kz** [comment]
Fixed i Master.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
