### ISSUE TITLE
Not all windows update info about peer

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#1160]
I have changed peer's name on bazaar then I want to unregister it, but in unregistering window i still see the old name, and I can't unregister it from bazaar.
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/e1e3bcbe-5b43-4017-8797-293d8bf0f460)

**Comment by AlinaPenkina** [comment]
![image](https://user-images.githubusercontent.com/34295807/41284405-0531ea1c-6e5b-11e8-81b7-14fe2137631a.png)

**Comment by Erkin97** [comment]
# PEER IS DIALOG IS DYNAMIC
It will refresh information about :
* Peer configs
* Peer status
* Peer name
* Peer environments

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
