### ISSUE TITLE
The default path for x2goclient

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1163]
the default path for x2goclient for MAC OS should be:

*/Applications/x2goclient.app*

**Comment by ibragim13kz** [comment]
Failed in Master. 
<img width="581" alt="screen shot 2018-06-19 at 6 39 54 pm" src="https://user-images.githubusercontent.com/33474101/41597885-84245374-73f0-11e8-8023-319381fedd79.png">

**Comment by akarasulu** [comment]
The path on Mac should be /Applications/x2goclient.app which works for me but I have to reset it in settings manually with each time I upgrade. Which sucks btw.

**Comment by Erkin97** [comment]
Both of them are correct, just make sure desktop ssh is working on master

**Comment by ibragim13kz** [comment]
Done in Master.

**Comment by ibragim13kz** [comment]
Done in Prod.
