### ISSUE TITLE
We need to add link to docs from CC 

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#1164]
For example I suggest to add link into "About" tab which will lead user to our documentation how to use Control Center properly.

**Comment by crioto** [comment]
My guess is to add "Help" section

**Comment by amangeldizhusubaliev** [comment]
Need to create documentation.

**Comment by satarovaAziza** [comment]
fixed on master.

**Comment by ibragim13kz** [comment]
Done in Prod.
