### ISSUE TITLE
Getting error message -> The Peer Manager is not yet ready for use. Please try again later.

### ISSUE THREAD

**Issue by khwari** [subutai-io/control-center#1201]
Can't create peer with CC.

[logs_09.txt](https://github.com/subutai-io/control-center/files/2117829/logs_09.txt)

[logs_10.txt](https://github.com/subutai-io/control-center/files/2117831/logs_10.txt)

**Comment by Erkin97** [comment]
@khwari can you confirm that everything is working now?

**Comment by khwari** [comment]
No problem

**Comment by ibragim13kz** [comment]
@Erkin97 So what was the problem?

**Comment by Erkin97** [comment]
@ibragim13kz we just reinstalled CC

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Didn't face in Prod.
