### ISSUE TITLE
SSH keys should not have symbols in their names

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1211]
## Current Behavior

When user generates ssh key with symbols in its name, a key can be deployed to an environment. However, when user tries to ssh into the containers, the process fails. 
## Possible Solution

ssh keys should not have symbols in names.
## Steps to Reproduce

1. Generate ssh key 
2. Put symbols in name
3. Deploy it to environment
4. ssh into the container of environment

![55555](https://user-images.githubusercontent.com/32430693/41758389-1e44485e-760a-11e8-9718-e0ea3f76a8c7.png)

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
