### ISSUE TITLE
CC can't update without write permission to the application folder

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1215]
## Current Behavior

CC offers a user to update Control Center in 'About' and even after user clicks 'Update Control Center' , CC keeps offering an update.  

## Possible Implementation

As it was mentioned in scrum meeting, this issue can be related to the fact that CC cannot delete the old version in machine due to the lack of privileges. 

<img width="704" alt="screen shot 2018-06-21 at 10 04 19 pm" src="https://user-images.githubusercontent.com/32430693/41758554-39f0674e-760b-11e8-8787-97bad0563c9a.png">

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Didn't face such problem in Prod. We'll reopen if needed.
