### ISSUE TITLE
We need to add logo to p2p stop/start buttons

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#1233]
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/81e39ecd-1d35-451e-b579-6e93ce0ea05f)

Something like this:
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/32f862e2-06b7-41ad-a42a-c07cab32d8a5)

**Comment by ibragim13kz** [comment]
Don't see any icon. Checked on Mac, Win10 and Mint.

**Comment by ibragim13kz** [comment]
Done in Master.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
