### ISSUE TITLE
Direct ssh access to containers running on your machine bypassing p2p client

### ISSUE THREAD

**Issue by Erkin97** [subutai-io/control-center#1234]
## Expected Behavior
Don't use p2p client to ssh into container which are already running on your machine. It happens when your machine is a peer.
Not only SSH but x2go should go directly as well.
## Current Behavior
p2p client does not work, so you can't connect

## Possible Solution
don't use p2p if container in your machine

## Steps to Reproduce

1. Build PeerOS on your machine
2. Build environment on that Peer
3. Try to ssh

**Comment by AlinaPenkina** [comment]
1. p2p doesn't stop  via CC.
2. When I finally stopped it, all envs became failed, seems it can't connect without p2p.
3. With p2p it always in "connecting" state

[CC-Logs.txt](https://github.com/subutai-io/control-center/files/2289425/CC-Logs.txt)

**Comment by AlinaPenkina** [comment]
Fixed.

**Comment by Almansherov** [comment]
Brought a peer up
registered it to bazaar
created an env using my own peer
and sshed into it after key deploy

![image](https://user-images.githubusercontent.com/32430693/47421852-0cab4180-d747-11e8-9cf3-754ae61cb930.png)

Fixed in master

**Comment by Erkin97** [comment]
Hi, guys :)
I think you got the description wrong. You need to be able to connect to the container using cc running inside of an rh. CC should not use P2P for that and it will use containers' ip address

**Comment by Almansherov** [comment]
@Erkin97 aah, all right. 
We will test it one more time then

**Comment by jadilet** [comment]
How to test:

1-step

Put the folllowing user configuration parameters to this file `vagrant-subutai.yml` (next to Vagrantfile):
(SUBUTAI_DESKTOP parameter will automatically install ControlCenter and Mate desktop)

`SUBUTAI_DESKTOP: true`
`SUBUTAI_ENV: master`

2-step

```
vagrant init subutai/stretch-master
vagrant up
```

3-step

Register your peer to the bazaar.
Create environment via bazaar to your registered peer.
Then check via ControlCenter to ssh to you container.

**Comment by Almansherov** [comment]
Followed the steps described above.
Everything worked on debian machine:

![image](https://user-images.githubusercontent.com/32430693/47477049-df16d480-d7e8-11e8-97ec-d155685a22b3.png)

Fixed in master

**Comment by Almansherov** [comment]
I ended up using control center inside of my peer with mate2go desktop. 
I checked the ssh and file transfer. 
Copied couple of files successfully:

![img_20181025_112520](https://user-images.githubusercontent.com/32430693/47477788-97924780-d7ec-11e8-8e46-bda144a4fda3.jpg)

**Comment by kurmanbekova6** [comment]
<img width="1199" alt="screen shot 2018-10-25 at 12 05 59 pm" src="https://user-images.githubusercontent.com/9501291/47479284-6b0f1780-d84e-11e8-9a50-931cb8cbdcd0.png">

**Comment by Almansherov** [comment]
Followed the steps above. 
Successfully finished it.
Fixed in master

**Comment by Almansherov** [comment]
Tested it two times during two days.
The build takes a lot of time, however, it ended up with successful settings.
Fixed
