### ISSUE TITLE
In settings window tab in common should be frame

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1246]
In settings window tab in common should be frame
![Screenshot_4.png](https://images.zenhubusercontent.com/5b0678434b5806bc2bd46eb3/6648b7e4-69a0-4950-b522-c9e508df4d3f)

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
