### ISSUE TITLE
CC Menu icons

### ISSUE THREAD

**Issue by amangeldizhusubaliev** [subutai-io/control-center#1262]
## Expected Behavior
All of the CC menu icons, except P2P's icon, must be painted into the same color.
## Current Behavior
On light themes everything seems good.
![cc_light](https://user-images.githubusercontent.com/38368928/42012586-ce331cd6-7aba-11e8-97d9-b6c1c2231b76.png)
On dark themes some of the icons just "disappear".
![cc_dark](https://user-images.githubusercontent.com/38368928/42012588-d05f4b7e-7aba-11e8-9ad3-cfd98882ff7e.png)
## Possible Solution
Just repaint icons.

**Comment by amangeldizhusubaliev** [comment]
we should rework all icons, make them smaller, remove unused ones.

**Comment by kurmanbekova6** [comment]
Fixed on Master

**Comment by ibragim13kz** [comment]
Done in Prod.
