### ISSUE TITLE
Toolbar about the each component with the description 

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1267]
We need to use an icon 'i' (just like in bazaar) so that when user points the icon, there appears a bar with information about the component and what does it used for. 

Sample:

![screenshot from 2018-06-28 12-21-38](https://user-images.githubusercontent.com/32430693/42016715-6c183306-7ace-11e8-9227-05931692f142.png)

**Comment by kurmanbekova6** [comment]
Fixed on Master

**Comment by ibragim13kz** [comment]
Done in Production.
