### ISSUE TITLE
Inform a user if CAPSLOCK is turned on 

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1277]
Due to the fact that users use at least one capital letter in their passwords, we need to make sure that no confusion caused to the users with their inputs. 
So ideally, would be cool to see an informative warning when capital letter is being typed.

![image 2](https://user-images.githubusercontent.com/32430693/42087589-734c787c-7bb8-11e8-9d42-76730ef3439c.png)

**Comment by amangeldizhusubaliev** [comment]
Coimplicated (Impossible) on mac.

**Comment by Almansherov** [comment]
This improvement might be available in the next project. For now it is not important enough
