### ISSUE TITLE
Versions of CC are different on Mac OS

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#1282]
This is related with the info list file.
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/99f65b4c-d03b-47ad-9f30-6dafd0a02c76)

**Comment by amangeldizhusubaliev** [comment]
To 'refresh' version after update, one should reboot system.

**Comment by kurmanbekova6** [comment]
Fixed
<img width="684" alt="screen shot 2018-07-14 at 4 55 22 pm" src="https://user-images.githubusercontent.com/9501291/42723785-2cf21dd4-8787-11e8-875f-7d067ccba12a.png">
<img width="596" alt="screen shot 2018-07-14 at 4 55 36 pm" src="https://user-images.githubusercontent.com/9501291/42723786-2e5abcbc-8787-11e8-96c2-ca4d464be30c.png">

**Comment by ibragim13kz** [comment]
Fixed in Prod.
