### ISSUE TITLE
CC eats a lot of PC's resources

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#1289]
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/75031a6c-3849-4759-9904-bcdeb3af6ab3)
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/e8f72a7a-eb77-4464-ae37-aded2a09d5f1)

**Comment by AlinaPenkina** [comment]
![image](https://user-images.githubusercontent.com/34295807/42406726-25d943e6-81cf-11e8-93bf-905d7751fd3b.png)

**Comment by AlinaPenkina** [comment]
This is RUBY eats CPU, I didn't up peer.

**Comment by Almansherov** [comment]
@AlinaPenkina So, we cannot do anything with this cpu waste. I want to put label "wontfix" or "research" and "discussion" and put this issue on Icebox pipeline. What do you think is it ok?

**Comment by AlinaPenkina** [comment]
Yes, I agree.

**Comment by ibragim13kz** [comment]
Moving into Icebox.

**Comment by Almansherov** [comment]
Duplicated #1839
