### ISSUE TITLE
Add Uninstall features to following components

### ISSUE THREAD

**Issue by jadilet** [subutai-io/control-center#1292]
* X2Go-Client
* Subutai-E2E
* Vagrant box

**Comment by kurmanbekova6** [comment]
How to use this feature?

**Comment by ibragim13kz** [comment]
@amangeldizhusubaliev CC shows ```Vagrant Subutai box was successfully uninstalled```, but it's still there.

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Done in Production.
