### ISSUE TITLE
Add Uninstall features to following components

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1293]
* Chrome
* Control Center

**Comment by Almansherov** [comment]
Control Center cannot delete itself. User can delete it just like any other application.

**Comment by ibragim13kz** [comment]
On Debian CC shows the message that Chrome installation has failed, but actually it was installed.

**Comment by ibragim13kz** [comment]
@amangeldizhusubaliev Similar thing on Win10: Chrome was removed, but CC says ```Uninstallation has failed```.

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
