### ISSUE TITLE
After sleeping mode on mac, user can not check old environments.

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1298]
After sleeping mode on mac, I can check my old environments because button became unclickable and looks like below: 
![Screen Shot 2018-07-02 at 9.25.51 AM.png](https://images.zenhubusercontent.com/5b0678434b5806bc2bd46eb3/dd0356ed-438f-4be8-b617-cfd3674a57a3)

**Comment by kurmanbekova6** [comment]
Can't check my environments on Mac. Seems not fixes @amangeldizhusubaliev 
<img width="337" alt="screen shot 2018-07-21 at 9 48 42 am" src="https://user-images.githubusercontent.com/9501291/43031824-8e4075e2-8ccb-11e8-9b5e-b61d2d500214.png">

**Comment by niclash** [comment]
Has this been tested on Linux and Windows as well? Or is it simply surfacing here because Mac users are much more prone to close the lid all the time?

**Comment by amangeldizhusubaliev** [comment]
@niclash, this issue presents only on mac.

**Comment by amangeldizhusubaliev** [comment]
Related: https://bugreports.qt.io/browse/QTBUG-63848

**Comment by ibragim13kz** [comment]
Need to observe.

**Comment by kurmanbekova6** [comment]
Did not face with this problem

**Comment by Almansherov** [comment]
Has left MacOS in sleep mode.
All of my envrionments are healthy and possible to check:

<img width="371" alt="screen shot 2018-10-31 at 11 36 20 am" src="https://user-images.githubusercontent.com/32430693/47768206-36450980-dd01-11e8-85aa-57ce4e0f6615.png">

Fixed in prod
