### ISSUE TITLE
On Ubuntu Master CC does not remember users account at all.

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1303]
When user login Master CC from Ubuntu and put a check mark on "Remember me" button, CC does not remember users account at all.

**Comment by amangeldizhusubaliev** [comment]
Cause of this problem: general user has no write permissions to `~/.config/subutai` folder. We'll investigate.

**Comment by ibragim13kz** [comment]
Fixed in Master. Checked on Ubuntu and Mint.
