### ISSUE TITLE
Not proper message in Unregister peer window

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#1305]
If user inputting wrong password CC shows "Network error"
Expected behavior:
Message that "Wrong username or password"
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/bcc9ab37-682a-4f55-a249-c2af0581bdda)

**Comment by kurmanbekova6** [comment]
Fixed on Master
![screenshot_7](https://user-images.githubusercontent.com/9501291/42491818-37379690-8438-11e8-8e97-4ea25992a295.png)

**Comment by ibragim13kz** [comment]
Fixed in Prod.
