### ISSUE TITLE
User can set up peer's resources which he doesn't have

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#1306]
If it is possible we need to check real machine resources before peer creating and when user wants to edit credentials of current peer.
Now I can create peer with HUGE resources, but in real i don't have its in my PC.
As I know such issue we had for vagrant plugin.
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/d99187e7-5bca-4506-b209-c861f41a65e5)

**Comment by AlinaPenkina** [comment]
I suggest to make this:
1. we need to scan the PC, and don't give access to user to build peer with more than this resources.
2. If user built 1 peer, some of his resources already in use. We can add some message that not all of your resources is available now. This is easy to implement.

**Comment by Erkin97** [comment]
* CC will check free ram space only on Linux and Windows
> This is not critical to check free space on Mac, since ram space will be assigned for peer dynamically

**Comment by ibragim13kz** [comment]
@Erkin97 
> This is not critical to check free space on Mac, since ram space will be assigned for peer dynamically 
Didn't get you. How RAM space can be assigned for peer dynamically?

**Comment by ibragim13kz** [comment]
@Erkin97 @jadilet @amangeldizhusubaliev Guys, we also need to check disk info.

**Comment by ibragim13kz** [comment]
I was able to create two peers with 2TB disk on each one, but actually I don't have such resources.
![screenshot_6](https://user-images.githubusercontent.com/33474101/43138941-3d03f02e-8f72-11e8-88c5-8038af26cd60.png)

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
