### ISSUE TITLE
Send arguments to binary file from SubutaiControlCenter

### ISSUE THREAD

**Issue by Erkin97** [subutai-io/control-center#1329]
* cli commands is not working in Linux, because SubutaiControlCenter does not send arguments to the binary file

**Comment by ibragim13kz** [comment]
After first check CC did not execute CLI commands, so @amangeldizhusubaliev suggested to download the fresh Master binary and try again, but it didn't help.

**Comment by Erkin97** [comment]
@ibragim13kz try to uninstall and install master again

**Comment by ibragim13kz** [comment]
@Erkin97 Implemented for Linux, but it's a little bit uncomfortable to move into CC application folder on Windows every time when I want to perform some commands via terminal.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
