### ISSUE TITLE
Progress bar got stuck.

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1335]
Progress bar got stuck.
![Screenshot from 2018-07-06 16-58-38.png](https://images.zenhubusercontent.com/5b0678434b5806bc2bd46eb3/ac4d3a35-e449-4293-a088-37cac9f6b5aa)
![Screenshot from 2018-07-06 16-53-34.png](https://images.zenhubusercontent.com/5b0678434b5806bc2bd46eb3/0a023a64-d708-4387-970a-8acc58bf942b)

**Comment by ibragim13kz** [comment]
@Erkin97 @amangeldizhusubaliev @jadilet We still face this problem when, for example, we do update or install a component. Behavior: progress bar is just stuck without displaying any progress there for a long time, after it just become completed and asks permission (for installation/update).

**Comment by ibragim13kz** [comment]
Doesn't matter on OS, it's everywhere.

**Comment by AlinaPenkina** [comment]
Fixed in master.

**Comment by Almansherov** [comment]
Have tested the fix on Debian, macos, ubuntu, and windows.
Components windows was not stuck or broken.
Fixed in prod
