### ISSUE TITLE
СС should not be deleted, before we close it.

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1342]
When user wants to delete CC,  Mac and Windows notifies user that CC in use  "The item Subutai Control Center can't be moved to the Trash because it's open." If CC  is running, user should not delete it.  It will be better, if CC also will notify user on Ubuntu to "quit" and install.

**Comment by amangeldizhusubaliev** [comment]
It is OS-specific. Try to uninstall running applications like Google Chrome, X2Go, Slack etc. In terminal you won't receive an error or warning, application will be removed. But opened window of this application will be working normally as long as you keep it opened.

**Comment by Erkin97** [comment]
#1346 duplicate
