### ISSUE TITLE
Quit Control Center appafter its uninstallation

### ISSUE THREAD

**Issue by ibragim13kz** [subutai-io/control-center#1346]
The issues is that CC doesn't quit after removing it from apps. We still can see it on the panel among other launched applications, even if it was deleted. 
So, it would be logically correct behavior if uninstallation will also close the client, because next installation causes errors if an app is already launched.

**Comment by Erkin97** [comment]
>you need install new deb packages

**Comment by ibragim13kz** [comment]
@Erkin97 Was this implemented for Windows also?

**Comment by ibragim13kz** [comment]
@Erkin97 Will not move it into another pipeline, just inform me when it's done for Windows.

**Comment by Erkin97** [comment]
> you need to reinstall cc to get this feature

**Comment by ibragim13kz** [comment]
Did reinstall CC, then deleted it from the Control Panel, so CC is still there. Furthermore, I still able to use it. For example, I did install Vagrant via CC.

**Comment by ibragim13kz** [comment]
Done for Windows also.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
