### ISSUE TITLE
HMTL code in Notifications

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1347]
So, there are some parts of html code in Notifications window: 

![image 3](https://user-images.githubusercontent.com/32430693/42432528-bd1a1be2-836c-11e8-9f16-47ff96f462e4.png)

Gotta get rid of them.

**Comment by amangeldizhusubaliev** [comment]
Notifications will be reworked, links will be underlined and painted to blue (as usual links). However they won't be clickable. To make them clickable we must completely rewrite notifications dialog window and change its structure.

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
