### ISSUE TITLE
Configuration of providers

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1373]
We have default provider -- VagrantBox. We need to add more alternatives. 
1) -- We add one more field in settings, where user can choose what hypervisor to use
2) -- We add hypervisors into 'Components', where user can install the necessary component
User has to deal with installation yet. Right after the first part, we start working on installation through CC

**Comment by alinas2403** [comment]
This is how it looks now
![screenshot from 2018-08-17 11-24-28](https://user-images.githubusercontent.com/42266015/44249581-50973d00-a212-11e8-80b8-6bffccb05c8a.png)

![screenshot from 2018-08-17 11-38-19](https://user-images.githubusercontent.com/42266015/44249603-6e64a200-a212-11e8-9661-8ea72705c698.png)

**Comment by Almansherov** [comment]
Have tested the settings configuration in cc.
Changed the providers
Changed the Browsers
and checked the components windows either the components of providers appeared or not
Fixed in prod
