### ISSUE TITLE
Shut down does not clean up

### ISSUE THREAD

**Issue by niclash** [subutai-io/control-center#1381]
Env; KDE on Linux Debian Stretch

If I shutdown Control Center when there are popup windows visible, those windows remain and can no longer be closed. All buttons in them are not responsive.

**Comment by niclash** [comment]
If Control Center is restarted, it somehow manages to re-attach to those dead popups and can be removed.

**Comment by ibragim13kz** [comment]
FIxed in Master.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
