### ISSUE TITLE
Peer Scope option in peer registration should became inactive after pressing "Register".

### ISSUE THREAD

**Issue by amangeldizhusubaliev** [subutai-io/control-center#1385]
## Expected Behavior
Peer Scope should became inactive after pressing "Register" button as other options do. 
## Current Behavior
![screenshot from 2018-07-14 10-08-04](https://user-images.githubusercontent.com/38368928/42720814-abe64a20-8750-11e8-9af5-ed7593d3b459.png)

**Comment by amangeldizhusubaliev** [comment]
Also there are some options in Peer creation dialog window that should became inactive after pressing "Create Peer".

**Comment by ibragim13kz** [comment]
Fixed in Prod.
