### ISSUE TITLE
Peer building progress bar got stuck with "Building virtual machine" status.

### ISSUE THREAD

**Issue by amangeldizhusubaliev** [subutai-io/control-center#1386]
## Expected Behavior
Progress bar must show 100% and disappear after successful building of Peer.
## Current Behavior
Peer is running, but I have 25% progress bar. 
![Screenshot from 2018-07-14 10-32-07.png](https://images.zenhubusercontent.com/5ad825c34b5806bc2bcfb9cb/c8c997fe-56a0-4dea-8c7f-fa50f5fc21e9)
## Steps to Reproduce
1. Start building peer.
2. Open its menu (My Peers -> Name). Try to do this step before Peer builds up.
3. Wait. Even after completing peer build, there will be progress bar.

**Comment by ibragim13kz** [comment]
@Erkin97 Sure.
[logs_15.txt](https://github.com/subutai-io/control-center/files/2213253/logs_15.txt)

**Comment by ibragim13kz** [comment]
Fixed in Prod.
