### ISSUE TITLE
Install providers to Vagrant

### ISSUE THREAD

**Issue by jadilet** [subutai-io/control-center#1395]
* For Parallels: 
    Required to install `vagrant-parallels` provider .
* For VMware:
    Required to install `vagrant-vmware-desktop` provider.
* For Libvirt:
    Required to install `vagrant-libvirt` provider.

**Comment by kurmanbekova6** [comment]
We now have only VMware Workstation provider. Waiting for other providers

**Comment by Almansherov** [comment]
Vagrant Libvirt installed:

![image](https://user-images.githubusercontent.com/32430693/48043741-cd6cef80-e14d-11e8-9ec7-9e928b25fe18.png)

VmWAre:

![image](https://user-images.githubusercontent.com/32430693/48043780-fdb48e00-e14d-11e8-9dd7-e60ebd17b351.png)

**Comment by kurmanbekova6** [comment]
![screenshot from 2018-11-14 14-29-54](https://user-images.githubusercontent.com/9501291/48469706-c616a780-e819-11e8-9682-a9e58f429b70.png)
![screenshot from 2018-11-14 14-31-56](https://user-images.githubusercontent.com/9501291/48469858-1130ba80-e81a-11e8-937c-cf37bacb15ea.png)

**Comment by kurmanbekova6** [comment]
<img width="602" alt="screen shot 2018-11-14 at 2 33 27 pm" src="https://user-images.githubusercontent.com/9501291/48469993-6e2c7080-e81a-11e8-91f3-1d727befbd45.png">
<img width="609" alt="screen shot 2018-11-14 at 2 34 30 pm" src="https://user-images.githubusercontent.com/9501291/48469999-6ff63400-e81a-11e8-89aa-d9dc94ddd7e2.png">
Tested in prod.
