### ISSUE TITLE
After restarting computer, Master CC itself does not launch on Windows. 

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1400]
After restarting computer, Master CC itself does not launch on Windows.

**Comment by amangeldizhusubaliev** [comment]
Checkbox is not working properly on Windows.

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
No such problem in Production.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
