### ISSUE TITLE
Symlinks in File Transfer

### ISSUE THREAD

**Issue by amangeldizhusubaliev** [subutai-io/control-center#1419]
Currently in File Transfer, you can see directories with "strange names" (`/var/lock -> /run/lock/`). They are symlinks. They should not be displayed in file transfer.

## Expected Behavior
There shouldn't be any symlinks.
## Current Behavior
screenshot by @ibragim13kz 
![42998290-7d4ae47e-8c3b-11e8-8e9d-525d39702071](https://user-images.githubusercontent.com/38368928/42999471-b62f05d2-8c3f-11e8-8a8c-67d7e773c7de.png)
## Possible Solution
Before adding directories into File Transfer list, make sure that they are real directories.
`ls -la` command may help with this.
## Steps to Reproduce
1. Create env
2. Deploy an SSH-key
3. Open File transfer

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
