### ISSUE TITLE
Edge (Win10) and Safari (MacOS).

### ISSUE THREAD

**Issue by amangeldizhusubaliev** [subutai-io/control-center#1421]
Add edge and safari to supported browsers.

**Comment by amangeldizhusubaliev** [comment]
Due to [Microsoft browser extension policy](https://docs.microsoft.com/en-us/legal/windows/agreements/microsoft-browser-extension-policy) we can not install/uninstall E2E plugin on Microsoft Edge browser. User will be notified that he/she should install E2E plugin by himself/herself once he/she chooses Microsoft Edge as a default browser in Control Center Settings.

**Comment by ibragim13kz** [comment]
Done in Master.

**Comment by ibragim13kz** [comment]
Done in Prod.
