### ISSUE TITLE
Rework x2goclient version and add xquartz 

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1434]
*Should not show checkboxes in places where you're waiting for vagrant to be installed first. maybe something like a `?` is better.
And X2Go-Client is not installed at all but it's showing that it is
On mac you might be confusing x2go with the presence of xquartz. Please see what you are using for the presence of x2go.
The OS is mac sierra
latest update*

![screen shot 2018-07-22 at 7 50 19 am](https://user-images.githubusercontent.com/32430693/43060033-d096db58-8e14-11e8-8aca-a5a37a675b81.png)

**Comment by Erkin97** [comment]
* Don't show installed for x2goclient version
* Check if xquartz installed

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Fixed in Production.
