### ISSUE TITLE
The message should be more informative

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1435]
![screen shot 2018-07-22 at 4 06 53 pm](https://user-images.githubusercontent.com/32430693/43060881-6ff24bd0-8e18-11e8-8510-5f996d8c796b.png)

**Comment by ibragim13kz** [comment]
Content of the message wasn't changed.

**Comment by amangeldizhusubaliev** [comment]
There is no any changes in message, but if user presses Yes, there will be small red warnings near the incorrect settings. 
![scr](https://user-images.githubusercontent.com/38368928/43500694-b7ae3e40-9573-11e8-9ebc-d314e799ed65.png)

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Fixed in Production.
