### ISSUE TITLE
Vagrant commands are not working with iTerm

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1436]
*FYI this last problem in screenshot above does not occur when I ssh with iTerm into the containers. That works just fine with iTerm settings as you see above. It is only when we try to SSH into the peer that things go wrong.*

![screen shot 2018-07-22 at 3 44 04 pm](https://user-images.githubusercontent.com/32430693/43061109-83b44b68-8e19-11e8-8ce2-1fd9f8bca4a0.png)

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
