### ISSUE TITLE
VMware Fusion installation on OS X

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1440]
We need VMware Fusion to be installed on OS X for multiple hypervisor usage.
More info about VMware Fusion:
https://my.vmware.com/en/web/vmware/info/slug/desktop_end_user_computing/vmware_fusion/10_0

**Comment by kurmanbekova6** [comment]
Fixed in Master

**Comment by Almansherov** [comment]
Successfully installed VMware fusion on mac:

<img width="614" alt="screen shot 2018-10-31 at 2 45 33 pm" src="https://user-images.githubusercontent.com/32430693/47776056-a9f41000-dd1b-11e8-9fc1-061d44f726f3.png">


Fixed in prod
