### ISSUE TITLE
VMware Workstation installation on Windows

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1442]
Windows users should have VMware Workstation in order to be able to use VMware as a hypervisor 

More info about VMware Workstation: https://www.vmware.com/products/workstation-pro/workstation-pro-evaluation.html

**Comment by AlinaPenkina** [comment]
In master.

**Comment by Almansherov** [comment]
Now it is available in Components:

![image 3](https://user-images.githubusercontent.com/32430693/47699112-d73ba380-dbdf-11e8-8bc5-040e864595ef.png)

Implemented in prod
