### ISSUE TITLE
[Windows] Subutai Control Center not deal with spaces properly on windows

### ISSUE THREAD

**Issue by jadilet** [subutai-io/control-center#1453]
## Expected Behavior

CC should deal with spaces properly.

## Current Behavior

I set SSH-keys storage path: `C:/Users/subutai/test check`
When ssh ing to container I got following errors:
```
Could not create directory '/home/subutai/.ssh'.
bash: checkknown_hosts: command not found

C:\Users\subutai>
```

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
