### ISSUE TITLE
Checkboxes should be empty after some process is done

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1473]
Let's say that a user installed some components and there still will be the checkboxes saved. 

They all should be empty

![screen shot 2018-07-25 at 17 34 28](https://user-images.githubusercontent.com/32430693/43245497-1582d8be-9074-11e8-8df9-ba3008153d73.png)

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
