### ISSUE TITLE
Users should be able to change the directory where VM needs to be created

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1485]
`We cannot lose sight of what needs to be done and just go with a function in a library.

This needs to be fixed and there probably also needs to be a configuration setting for where this the machines will need to go that the user can modify if the default does not work for them. This is a serious issue.
I've reallocated space from other places thanks to lvm but this is a critical issue that needs to be included in the next release.
Completely unacceptable for the product to not have this flexibility.`  -- from Slack

Where is CC trying to build this new VM? 
![screen shot 2018-07-27 at 7 35 54 pm](https://user-images.githubusercontent.com/32430693/43354530-92b9948a-9213-11e8-8f71-6e054f0d8c9d.png)
![12431243](https://user-images.githubusercontent.com/32430693/43354534-9ca8419e-9213-11e8-9268-d83e4e6a5051.png)

**Comment by Erkin97** [comment]
![image](https://user-images.githubusercontent.com/22586805/43635945-799a59b6-9732-11e8-8480-05d4bca59b0e.png)
* Added option in settings

**Comment by kurmanbekova6** [comment]
Fixed in Master

**Comment by Almansherov** [comment]
Created a peer using different Vm storage. tried on all OSs. 
Fixed in prod
