### ISSUE TITLE
Vagrant VMware utility installation for VMware provider  

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1491]
For more information:
*https://www.vagrantup.com/docs/vmware/vagrant-vmware-utility.html*

**Comment by kurmanbekova6** [comment]
Fixed in Master

**Comment by kurmanbekova6** [comment]
Can not install Vagrant VMware utility for Linux

**Comment by kurmanbekova6** [comment]
Switched to VMware Workstation provider (CC=>Settings)
Installed needed components (CC)
Installed Vagrant -VMWare-workstation-licence 
Installed Vagrant VMWare Utility
Brought peer up
Reinstalled all components 
Tried it several times
Fixed in Master

**Comment by Almansherov** [comment]
Followed the described steps above^ 

![image](https://user-images.githubusercontent.com/32430693/47699599-58e00100-dbe1-11e8-815e-dcde0bc14fb6.png)

fixed in prod

**Comment by kurmanbekova6** [comment]
Successfully installed, uninstalled VMware Utility.
Tested in master

**Comment by kurmanbekova6** [comment]
Successfully reinstalled VMWare utility on all Oss.
