### ISSUE TITLE
Safari E2E installation

### ISSUE THREAD

**Issue by amangeldizhusubaliev** [subutai-io/control-center#1503]
## Expected Behavior
E2E plugin installation must be as easy as possible. 

## Current Behavior
Sometimes when install button is pressed CC notifies that it is running installation scripts, but nothing happens. And then CC notifies that E2E plugin was installed. However it was not. 

## Possible Solution
Need to properly quit Safari before E2E installation.

## Steps to Reproduce
1. Chose Safari as a default browser in CC Settings.
2. Go to Components and begin Subutai E2E installation.

## Possible Implementation
Need to rework Safari quitting script.

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Done in Prod.
