### ISSUE TITLE
CC branch changing

### ISSUE THREAD

**Issue by amangeldizhusubaliev** [subutai-io/control-center#1504]
## Expected Behavior
Branch changing must change branch for all functions of CC.

## Current Behavior
If one changes branch from stage to production and starts building peer, it will be built with stage configurations, hence it can not be registered on production master.

## Possible Solution
Need to store some global variable which will contain CC branch status. 

## Steps to Reproduce
1. Install master CC.
2. Launch it with `SubutaiControlCenter --mode production`
3. Try to build and register peer on bazaar.

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Done in Prod.
