### ISSUE TITLE
Add possibility to register a peer as 'Shared' via Control-Center

### ISSUE THREAD

**Issue by ibragim13kz** [subutai-io/control-center#1523]
## Expected Behavior
This feature was implemented by Subutai Console recently, so, CC also needs to add it,

## Current Behavior
At the moment it's possible to register a peer only as ```Public``` and ```Private```.

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by Almansherov** [comment]
Created a peer and registered it to bazaar with `Shared` scope:

![image](https://user-images.githubusercontent.com/32430693/47697991-714d1d00-dbdb-11e8-91f2-b305acdd3b81.png)

Was tested on Debian, Ubuntu, MacOS, and Windows
