### ISSUE TITLE
Add Configuration of VM storage path on VMware

### ISSUE THREAD

**Issue by jadilet** [subutai-io/control-center#1540]
CC can configure VM storage of Virtualbox. We should also add configuration VM storage path of VMware.

**Comment by kurmanbekova6** [comment]
Fixed in Master

**Comment by Almansherov** [comment]
Windows:

![image 4](https://user-images.githubusercontent.com/32430693/47699207-2b468800-dbe0-11e8-9017-e02aebef0609.png)

**Comment by Almansherov** [comment]
Brought a peer up using vmware on the other vm storage.
fixed in prod
