### ISSUE TITLE
Master CC gets stuck on Windows

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1563]
While installing Vagrant Subutai Box CC gets stuck on Windows.

How to reproduce:
1.  Install Vagrant and restart machine
2. Install Vagrant Subutai Box
[logs_17.txt](https://github.com/subutai-io/control-center/files/2289246/logs_17.txt)

**Comment by amangeldizhusubaliev** [comment]
Vagrant issue.

```
The machine index which stores all required information about
running Vagrant environments has become corrupt. This is usually
caused by external tampering of the Vagrant data folder.

Vagrant cannot manage any Vagrant environments if the index is
corrupt. Please attempt to manually correct it. If you are unable
to manually correct it, then remove the data file at the path below.
This will leave all existing Vagrant environments "orphaned" and
they'll have to be destroyed manually.

Path: C:/Users/subutai/.vagrant.d/data/machine-index/index
```

**Comment by kurmanbekova6** [comment]
After switching provider, CC gets stuck 
[logs_10.txt](https://github.com/subutai-io/control-center/files/2289242/logs_10.txt)

**Comment by AlinaPenkina** [comment]
[logs.txt](https://github.com/subutai-io/control-center/files/2289333/logs.txt)

**Comment by AlinaPenkina** [comment]
After installing VMvare also stuck

**Comment by kurmanbekova6** [comment]
1. Installed all CC components.
2 .Checked all buttons.
3. Reinstalled components.
4. Installed them again.
5. Checked file transfer
6. Checked ssh
7. Brought peer up successfully without freeze

Fixed in Master

**Comment by kurmanbekova6** [comment]
1. Installed all CC components.
2 .Checked all buttons.
3. Reinstalled components.
4. Installed them again.
5. Checked file transfer
6. Checked ssh
7. Brought peer up successfully without freeze

Fixed in Master

**Comment by Almansherov** [comment]
Repeated the steps described above^

![image 5](https://user-images.githubusercontent.com/32430693/47700922-2edd0d80-dbe6-11e8-9179-667adcb27d41.png)

Fixed in prod
