### ISSUE TITLE
Parallels installation on OS X

### ISSUE THREAD

**Issue by jadilet** [subutai-io/control-center#1564]
We need Parallels to be installed on OS X.
More info about Parallels:
https://www.parallels.com/products/desktop/download/

**Comment by Almansherov** [comment]
Successfully installed Parallels:

<img width="610" alt="screen shot 2018-11-01 at 3 10 33 pm" src="https://user-images.githubusercontent.com/32430693/47843041-6e455e80-dd8c-11e8-9653-7f57be3e9e84.png">

Fixed in master

**Comment by kurmanbekova6** [comment]
Tested in prod.
<img width="614" alt="screen shot 2018-11-14 at 1 03 43 pm" src="https://user-images.githubusercontent.com/9501291/48465647-c14bf680-e80d-11e8-9a1d-0511f9bd80bd.png">
