### ISSUE TITLE
Update cdn links

### ISSUE THREAD

**Issue by Erkin97** [subutai-io/control-center#1571]
* After new cdn raw section is working we need to update cnd links to the new cdn links, because old cdn will not work soon
refer https://github.com/optdyn/hub/issues/6835

**Comment by Almansherov** [comment]
From Control Center side the binaries should be renamed according to IPFS file names:

SubutaiControlCenter.exe - > SubutaiControlCenter-$branchname.exe
SubutaiControlCenter_osx -> SubutaiControlCenter-$branchname_osx
SubutaiControlCenter - > SubutaiControlCenter-$branchname

**Comment by amangeldizhusubaliev** [comment]
**We need new REST points to be deployed to prod.** Our cdn is migrating to ipfs, and current REST points will become unavailable with termination of old cdn. Team Bazaar have implemented new REST on dev branch. We need them also on master and production.

**Comment by maksimyugai** [comment]
On devbazaar all work fine? If yes, then on master this rest will available after 24 Aug and on prod after 3 Sep.

**Comment by amangeldizhusubaliev** [comment]
@maksimyugai, CDN on devbazaar is working fine for us.

**Comment by amangeldizhusubaliev** [comment]
@maksimyugai, https://devbazaar.subutai.io/rest/v1/cdn/raw?name=subutai-control-center-dev.deb
Version is incorrect, should be 7.1.5, but it is not critical.

**Comment by maksimyugai** [comment]
@amangeldizhusubaliev it's not an original file version, it's file version inside BZR.

**Comment by amangeldizhusubaliev** [comment]
@maksimyugai can we edit this version? It came out that we need the versions of binaries and packages of CC. Just like in the old CDN: https://cdn.subutai.io:8338/kurjun/rest/raw/info?name=subutai-control-center-dev.msi.

**Comment by kurmanbekova6** [comment]
1. Installed Master CC.
2. Checked installation of all components of CC on Mac OS, Linux, Windows.
Fixed in Master

**Comment by Almansherov** [comment]
Checked all the components installations on all OSs
fixed in prod
