### ISSUE TITLE
Notifications about the users resources (RAM) 

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1572]
We need to reconsider notifications during the peer creation through Control Center. 
Some notes from Liz:

Case 1: User entry is 2048 or more, available RAM is 2048 or more
- Ok
Case 2: User entry is less than 2048, available RAM is 2048 or more
= “RAM cannot be less than 2048 MB.”
Case 3: User entry is more than available RAM, available RAM is 2048 or more
- “RAM exceeds the Available # MB.”
Case 4: User entry is 2048 or more, available RAM is less than 2048
- “Available RAM (# MB) cannot be less than 2048 MB.”
Case 5: User entry is less than 2048, available RAM is less than 2048
= “Available RAM (# MB) cannot be less than 2048 MB.”

**Comment by alinas2403** [comment]
Case 1:
![screenshot from 2018-08-17 12-06-43](https://user-images.githubusercontent.com/42266015/44250460-3fe8c600-a216-11e8-8874-8c16990a065b.png)

**Comment by Almansherov** [comment]
This issue was fixed in #1681
