### ISSUE TITLE
Wrong information in peer information window 

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1575]
There is `IP` in `SSH info` in the peer information window.

It is not an IP itself. It should be fixed to proper message. 

Hostname maybe

**Comment by alinas2403** [comment]
This how it looks like (My Peers)

![image](https://user-images.githubusercontent.com/42266015/44251204-59d7d800-a219-11e8-8ab1-6415bd6a252b.png)

**Comment by Almansherov** [comment]
Not relevant anymore
