### ISSUE TITLE
Peer name

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1577]
The text in `Peer Information` looks like it can be edited, but actually it cannot be changed.

Easy fix

**Comment by ux-scott** [comment]
This is a problem on several of the CC dialogs, identified in the UX review doc.

**Comment by alinas2403** [comment]
This how it looks like
![image](https://user-images.githubusercontent.com/42266015/44250667-0cf30200-a217-11e8-9a67-9ca363943faa.png)

**Comment by Almansherov** [comment]
Was fixed already
