### ISSUE TITLE
Can not create peer from the first attempt

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1580]
After switching to VMWare Workstation user can not create peer from the first attempt, need to recreate it 2-3 times, only then can create.
![Screenshot_2.png](https://images.zenhubusercontent.com/5b0678434b5806bc2bd46eb3/33059e16-cfff-4d5a-82fd-dfa44a33d6e7)

**Comment by jadilet** [comment]
This issue related to https://github.com/hashicorp/vagrant/issues/8642

**Comment by Almansherov** [comment]
Hashicorp issue was fixed, so we have not met this bug. Successfully created a peer
