### ISSUE TITLE
When we switch providers, the names of the providers  appear later.

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1590]
When we switch providers, the names of the providers  appear later. Page looks broken.

Expected behavior:
They should all appear together or should not appear until refresh.
![Screenshot_7.png](https://images.zenhubusercontent.com/5b0678434b5806bc2bd46eb3/67c88978-9051-4cea-9e83-f63f2975d135)

**Comment by Almansherov** [comment]
Checked on ubuntu, debian, macos, and windows.
fixed in prod.
