### ISSUE TITLE
After installation VMware on Osx not showing version

### ISSUE THREAD

**Issue by jadilet** [subutai-io/control-center#1597]
## Expected Behavior

After installation, In Components dialog should show VMware version.
## Current Behavior

![bug](https://user-images.githubusercontent.com/6593519/44322824-20010e80-a471-11e8-8879-2f0683d1eb8a.png)

## Steps to Reproduce

1. Install VMware from Components Dialog

**Comment by AlinaPenkina** [comment]
In Windows also doesn't show version of Vagrant Subutai Box.
![image](https://user-images.githubusercontent.com/34295807/44453977-2b446d80-a61c-11e8-9d5f-9fda3e726c84.png)

**Comment by AlinaPenkina** [comment]
[logs_15.txt](https://github.com/subutai-io/control-center/files/2309997/logs_15.txt)

**Comment by AlinaPenkina** [comment]
Fixed in master.

**Comment by Almansherov** [comment]
After installation of components the versions are here:


<img width="605" alt="screen shot 2018-10-31 at 4 09 52 pm" src="https://user-images.githubusercontent.com/32430693/47781241-73bc8d80-dd27-11e8-820d-d4999b1965ff.png">

fixed in prod
