### ISSUE TITLE
CC provides wrong format of path (Vagrant subutai plugin fails while parsing yml file).

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#1599]
`SUBUTAI_DISK_PATH : "C:\Users\qa\VirtualBox VMs"` this should be like:
`SUBUTAI_DISK_PATH : "C:/Users/qa/VirtualBox VMs"`

User can't create peer with this.

**Comment by kurmanbekova6** [comment]
Fixed in Master

**Comment by Almansherov** [comment]
Brought the peers up using different storages
Fixed in prod.
Overmore, now the storage can be changed
