### ISSUE TITLE
Can not register peer to Bazaar

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1602]
Can not register peer to Bazaar via Control Center(Production) on Windows, shows "Network error. Code: Internal Server Error"

![Screenshot_5.png](https://images.zenhubusercontent.com/5b0678434b5806bc2bd46eb3/88d13a29-eaed-4443-a81a-7c8b3049ec9e)
[logs_12.txt](https://github.com/subutai-io/control-center/files/2302025/logs_12.txt)

**Comment by Almansherov** [comment]
I faced the issues with registration using cc master. 
I created a peer via cc and wanted to register it but faced the error message.
Then we repeated the same steps on ubuntu and have got the same error. 

![2](https://user-images.githubusercontent.com/32430693/45621238-405ac380-ba45-11e8-8d10-3aaea0c17746.png)
Logs:
[karaflogs2018-09-17 04_48_01.txt](https://github.com/subutai-io/control-center/files/2388403/karaflogs2018-09-17.04_48_01.txt)

**Comment by amangeldizhusubaliev** [comment]
We have found the root of the problem: if "remember me" was unchecked while logging in, CC uses last "remembered" password to register a peer, i.e. it will not use password of current user.

How to reproduce: 
1) Login with "remember me" checked.

**Comment by Almansherov** [comment]
Followed the steps above and have not faced any errors with registration of peer via cc. 
Fixed on master

**Comment by Almansherov** [comment]
After creation of peer (vmware provider) , I registered the peer to bazaar. 
Overmore, during the previous tests, we have registered bunch of peers on bazaar. 
No errors were faced.
Fixed in prod
