### ISSUE TITLE
When user wants to delete Vagrant  WMWare Desktop, VMWare Workstation, Vagrant VMWare Utility progress bar gets stuck.

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1609]
When user wants to delete Vagrant  WMWare Desktop, VMWare Workstation, Vagrant VMWare Utility progress bar gets stuck. Uninstall components for these components does not work.  
![screenshot_20180822_122735](https://user-images.githubusercontent.com/9501291/44447611-8d947280-a60a-11e8-9414-5d355f0936dc.png)

**Comment by kurmanbekova6** [comment]
![screenshot_20180822_154405](https://user-images.githubusercontent.com/9501291/44456627-dce69d00-a622-11e8-8f0f-ebdfffcc0a62.png)

**Comment by kurmanbekova6** [comment]
1. Switched between Hypervisors.
2. Installed Components of CC.
3. Deleted them.

Did not face with stuck. Only installation of VMWare takes a long time. Fixed in Master.

**Comment by Almansherov** [comment]
Repeated the steps above on all OSs.
has not faced any troubles
fixed in prod.
