### ISSUE TITLE
Can't uninstall Vagrant VM ware Utility

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#1617]
@amangeldizhusubaliev Said that I don't have installed Vagrant VM ware Utility. So when it shouldn't be available for deletion.
https://files.slack.com/files-pri/T6FV09UF3-FCDHA1Q2F/download/ice_video_20180823-120004.webm

**Comment by Almansherov** [comment]
was able to uninstall and install again the component
fixed in prod
