### ISSUE TITLE
Isolate version checks in other threads

### ISSUE THREAD

**Issue by amangeldizhusubaliev** [subutai-io/control-center#1622]
## Expected Behavior
Components window shouldn't wait for version checks.

## Current Behavior
Currently Components window waits for version checking threads to finish. Some checks may run very slow, causing freezes.

## Possible Implementation
Create new class for version checks, with respective signals and slots.

**Comment by kurmanbekova6** [comment]
Fixed in Master

**Comment by Almansherov** [comment]
Before this fixe the components window was extremely slow.
Now it loads around 3 seconds depending on internet speed.
fixed in prod.
