### ISSUE TITLE
Peers is not displayed

### ISSUE THREAD

**Issue by ekadyrkulov** [subutai-io/control-center#1639]
I have problem creating peer. Peers is not displayed.
I reproduced (Windows OS) in prod repo 

![2018-08-28_164506.png](https://images.zenhubusercontent.com/5b713aba134f1f42006ddaa3/c342c87c-110b-4c3b-91c9-1757de7c4aea)![2018-08-28_164622.png](https://images.zenhubusercontent.com/5b713aba134f1f42006ddaa3/eab21f71-21d4-428d-92a5-a962a3e17d08)![2018-08-28_164849.png](https://images.zenhubusercontent.com/5b713aba134f1f42006ddaa3/068e7d6d-9e5b-4591-90c4-89504f9f63f4)

**Comment by ekadyrkulov** [comment]
I found problem about creation peer in masterbazaar. Peer is long create and there is no reaction

**Comment by kurmanbekova6** [comment]
Created several peers. Did not face with this problem. Need to observe, moving to  "in Master Test"

**Comment by kurmanbekova6** [comment]
Created peers, all peers were displayed on CC.
Registered,unregistered them.

**Comment by Almansherov** [comment]
All the peers created while testings were displayed in cc.
Issue fixed in prod
