### ISSUE TITLE
Don`t give the ability to user create peer if VT-x in BIOS disabled

### ISSUE THREAD

**Issue by absidish** [subutai-io/control-center#1645]
Problem: 
If VT-x is disabled in BIOS, CC cannot create peers. Peer creation process will fail with an error
```
The system cannot find the path specified.
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr are shown below.

Command: ["startvm", "a5d219ac-d6fd-4ab9-bc8e-000dd612fdae", "--type", "headless"]

Stderr: VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
```

Solution:

I suggest don`t give the ability to user create peer if VT-x in BIOS disable and show this info somewhere is CC panel

**Comment by efeefe** [comment]
We should include this in the getting started documentation, and if possible let CC user know how to enable it (perhaps a link from CC to the proper documentation page when it's available?)

**Comment by MarilizaC** [comment]
Not in the Getting Started page, just a note on a doc page, probably with a link to a third-party doc. This is a prerequisite for VMs in general and this is system-specific. We do not have control over this feature, meaning it's not managed by the company. It could be changed or removed at any time without our knowledge, so we can't say that it's our prerequisite.

**Comment by amangeldizhusubaliev** [comment]
I have been searching for a way to know virtualization status in bios via linux built-in tools, and did not succeeded. There is a file `/proc/cpuinfo` which can help us to determine if cpu supports virtualization, but it will not help much, because virtualization can be supported by cpu and also can be disabled in BIOS.

**Comment by Almansherov** [comment]
According to the comment of Amangeldi, this issue cannot be fixed
