### ISSUE TITLE
Update p2p on Linux using Debian package

### ISSUE THREAD

**Issue by crioto** [subutai-io/control-center#1651]
Currently CC replaces p2p binary on Linux, but we need to support installation of debian package. Don't forget about supporting previous way for updates for users who didn't switch to new debian package yet.

**Comment by Almansherov** [comment]
On Debian OS updated CC itself and P2P Daemon via Control Center (Master):

![image 2](https://user-images.githubusercontent.com/32430693/45151273-aba7c880-b1ef-11e8-8a58-8e538586b409.png)

Have got updates without any difficulties:

![image 3](https://user-images.githubusercontent.com/32430693/45151405-093c1500-b1f0-11e8-99d1-2e1dea4f1388.png)

**Comment by Almansherov** [comment]
Reopened by mistake. Closing
