### ISSUE TITLE
X2Go client failing to access to the Mate container when client have multiple envs. 

### ISSUE THREAD

**Issue by zubaidullo** [subutai-io/control-center#1655]
When CC client using Remote Desktop feature with multiple desktop environments, having above described issue.
Reason (not 100% sure yet):

CC generating sessions file in directory $HOME/.x2goclient
When trying access with the second environment, it's overwriting configurations. (probably this file is confusing parameters of two environments)

To test:
Create env with Mate BP (don't forget to add you SSH key)
Test Remote Desktop (should be success)
Create another env with Mate BP (don't forget to add you SSH key)
Test Remote Desktop
Here the problem starts, one of environments will have problem with X2GO client

original issue: https://github.com/optdyn/hub/issues/7007

**Comment by jadilet** [comment]
Added clean old session file before opening new session X2Go.
Now CC generates a new session file every  X2Go session.

**Comment by Almansherov** [comment]
created two mate2go blueprints one after another.
added ssh keys 
and tested the remote desktop function
fixed in prod
