### ISSUE TITLE
Give unique port numbers to peers.

### ISSUE THREAD

**Issue by amangeldizhusubaliev** [subutai-io/control-center#1663]
## Expected Behavior
All peers should have distinct port numbers.

## Current Behavior
It is possible to create two peers with the same port number. That makes CC work incorrectly with these two peers.

## Steps to Reproduce
1. Create peer via CC. 
2. Stop it. Make sure that virtual machine is powered off.
3. Create another peer.
They'll have same port numbers.

**Comment by Almansherov** [comment]
Created two peers one after another. One of them has got port number 9999 and the second one has got 10000. 
Fixed in prod 
tested on all oss
