### ISSUE TITLE
When we minimize popup of CC, popup gets hidden behind taskbar on Windows 

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1666]
When we minimize popup of CC, popup gets hidden behind taskbar on Windows 
![CC.png](https://images.zenhubusercontent.com/5b0678434b5806bc2bd46eb3/0dc45e30-8762-4528-b238-e5b3eb2960bc)

**Comment by Almansherov** [comment]
Tested on Windows with prod cc. 
Fixed in prod
