### ISSUE TITLE
Button size is different on Linux .

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1672]
Components button's size are different on Linux . 
![Screenshot from 2018-09-11 13-34-32.png](https://images.zenhubusercontent.com/5b0678434b5806bc2bd46eb3/113babec-e111-4c38-8115-36cbcd0b1a38)

**Comment by kurmanbekova6** [comment]
Fixed in Master

**Comment by Almansherov** [comment]
Fixed in prod: 

![image 7](https://user-images.githubusercontent.com/32430693/47785114-b05f9900-dcd5-11e8-949c-92530d5c3b25.png)
