### ISSUE TITLE
[Hyper-V] Use IP address of peers

### ISSUE THREAD

**Issue by jadilet** [subutai-io/control-center#1675]
On Hyper-V not supporting port-forwarding (Vagrant). 

## Expected Behavior

CC should get  `IP` from peer's `generated` file.
CC should use peer url like `https://IP_PEER:8443`
## Current Behavior

CC get `port` from peer's `generated` file.
CC use peer url like `https://localhost:PORT`

**Comment by Almansherov** [comment]
After bringing up a peer, I changed the IP in `generated` file and after that peer just got into `NOT READY` state and has not come back:

![image](https://user-images.githubusercontent.com/32430693/46462430-515e4100-c776-11e8-9ec0-c7d68315a57f.png)

Failed in stage

**Comment by Almansherov** [comment]
*One more detail*
The peer is online in bazaar, which is weird (even though cc shows that it is not running).
I already built an environment on it 

![image](https://user-images.githubusercontent.com/32430693/46467649-25958800-c783-11e8-9e5f-55c66c3f0adb.png)

**Comment by Almansherov** [comment]
Still `NOT READY` stage:

![image](https://user-images.githubusercontent.com/32430693/46470137-6b098380-c78a-11e8-9836-4e5638bcd8a9.png)

**Comment by Almansherov** [comment]
edited `generated.yml` and added `_IP_HYPERV` :

![image](https://user-images.githubusercontent.com/32430693/46782692-f8455e80-ccdb-11e8-9b96-8f1abd61d2f9.png)

Fixed in master

**Comment by Almansherov** [comment]
Followed all the steps above^
After peer became online, I edited the yml file, and reloaded the peer.
The peer has got a new ip address.
Fixed in prod
