### ISSUE TITLE
When Disk gb not suitable for peer creation, user gets confused by these messages. 

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1681]
When Disk gb not suitable for peer creation, user gets confused by these messages. Can you also add 
another suitable message? For example: There is insufficient disk space.
![1.png](https://images.zenhubusercontent.com/5b0678434b5806bc2bd46eb3/c027ec12-7d4c-4adf-8176-c286548d9549)
![2 (1).png](https://images.zenhubusercontent.com/5b0678434b5806bc2bd46eb3/1c59fada-feda-49b2-9671-d7a80c58d900)

**Comment by amangeldizhusubaliev** [comment]
Duplicate #1572
