### ISSUE TITLE
Use new Console REST API for peer register and unregister

### ISSUE THREAD

**Issue by jadilet** [subutai-io/control-center#1706]
Now CC uses following REST API for peer register and unregister.
Because following REST API is deprecated.

```
/rest/v1/hub/unregister?sptoken=
/rest/v1/hub/register?sptoken=
```

We should use new Console REST API:

```
/rest/v1/bazaar/unregister?sptoken=
/rest/v1/bazaar/register?sptoken=
```

**Comment by Almansherov** [comment]
Successfully registered a peer 
Fixed in master

**Comment by kurmanbekova6** [comment]
![screenshot_22](https://user-images.githubusercontent.com/9501291/50535325-3cc1f700-0b73-11e9-996a-f0cf247bb71c.png)
Fixed in prod.
