### ISSUE TITLE
User can not unregister peer from bazaar via Control Center if it has console environment 

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1714]
Currently we can not unregister peer from bazaar via CC  if peer has console environment.

_Expected behavior:_

CC should allow unregister peer if it has console environment.

_How to reproduce:_

1. Bring peer up.
2. Register peer to bazaar.
3. Create environment from Console side.
4. Unregister peer.

_P.S. Make sure peer does not have environment which was created from bazaar (if it is old peer)._

**Comment by Almansherov** [comment]
Followed the steps above.
Successfully unregistered my peer with 2 console environments:

![image](https://user-images.githubusercontent.com/32430693/46783835-9fc49000-cce0-11e8-8eb4-5e2fc2136efc.png)

Fixed in master

**Comment by Almansherov** [comment]
Followed the steps described above^

![image](https://user-images.githubusercontent.com/32430693/47715431-cb66d600-dc0d-11e8-902d-55c812709ec5.png)

Fixed in prod
