### ISSUE TITLE
Peer brings up without any error, but peer's status not created on Mac OS. 

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1716]
_How to reproduce:_

Bring peer up.
Check peer.

Peer's status:  not created. 
<img width="596" alt="screen shot 2018-10-04 at 2 43 36 pm" src="https://user-images.githubusercontent.com/9501291/46462689-e9464400-c7e3-11e8-92ce-156d76067cfa.png">

```
id       name    provider   state   directory
-------------------------------------------------------------------------------
eb3d28c  default virtualbox running /Users/qa/Subutai-peers/subutai-peer_Panda
```

**Comment by kurmanbekova6** [comment]
Fixed in Master.

Peer's status Running.
<img width="588" alt="screen shot 2018-10-16 at 10 56 16 am" src="https://user-images.githubusercontent.com/9501291/47006706-5baa1300-d158-11e8-8309-9ae78ddddaf3.png">

**Comment by kurmanbekova6** [comment]
![screen shot 2018-10-18 at 4 04 45 pm](https://user-images.githubusercontent.com/9501291/47148464-a5444c00-d285-11e8-9637-22b44da64397.png)

```qas-MacBook-Pro:~ qa$ vagrant global-status
id       name    provider   state   directory                                 
------------------------------------------------------------------------------
7e3a895  default virtualbox running /Users/qa/Subutai-peers/subutai-peer_Brew 
03fe099  default virtualbox running /Users/qa/Subutai-peers/subutai-peer_Oct```

**Comment by kurmanbekova6** [comment]
[logs_15.txt](https://github.com/subutai-io/control-center/files/2491556/logs_15.txt)
[logs_16.txt](https://github.com/subutai-io/control-center/files/2491557/logs_16.txt)

**Comment by jadilet** [comment]
Can you reproduce with new deployed master ControlCenter? (on logs show status peer)

**Comment by kurmanbekova6** [comment]
Fixed in Master
<img width="582" alt="screen shot 2018-10-24 at 5 04 09 pm" src="https://user-images.githubusercontent.com/9501291/47426423-f1741c80-d7ae-11e8-940f-df1f435c02e3.png">
<img width="587" alt="screen shot 2018-10-24 at 5 04 29 pm" src="https://user-images.githubusercontent.com/9501291/47426426-f33de000-d7ae-11e8-9468-619746050710.png">

**Comment by Almansherov** [comment]
Followed the steps described above^
as a result, has got a peer with running state:

<img width="588" alt="screen shot 2018-10-31 at 5 17 46 pm" src="https://user-images.githubusercontent.com/32430693/47784805-e7af6380-dd30-11e8-890b-cf81bdef05a1.png">

fixed in prod
