### ISSUE TITLE
Add KVM installation on linux

### ISSUE THREAD

**Issue by jadilet** [subutai-io/control-center#1724]
* Installation guide for Ubuntu:
https://help.ubuntu.com/community/KVM/Installation

* Installation guide for Debian:
https://wiki.debian.org/KVM

**Comment by Almansherov** [comment]
Successfully installed the components:

![image](https://user-images.githubusercontent.com/32430693/47894764-912a4e00-de32-11e8-973d-507536ba67a9.png)

Fixed in master

**Comment by kurmanbekova6** [comment]
[logs_12.txt](https://github.com/subutai-io/control-center/files/2541268/logs_12.txt)
Could not install KVM on Ubuntu 1604

**Comment by Almansherov** [comment]
KVM was successfully installed on Ubuntu:

![screenshot from 2018-11-05 17-40-46](https://user-images.githubusercontent.com/32430693/47996231-761f3e80-e0bd-11e8-9992-6805aab20537.png)

Fixed in master

**Comment by kurmanbekova6** [comment]
![screenshot from 2018-11-14 14-50-07](https://user-images.githubusercontent.com/9501291/48470804-a339c280-e81c-11e8-9179-2502acbf8068.png)
Tested in prod
