### ISSUE TITLE
Add Uninstall feature to KVM

### ISSUE THREAD

**Issue by jadilet** [subutai-io/control-center#1726]

**Comment by Almansherov** [comment]
Uninstall is completely broken on Debian

![image](https://user-images.githubusercontent.com/32430693/47896038-8a530980-de39-11e8-94ba-fd388dc75339.png)

I changed the provider in settings
Installed the components and started uninstalling.
The last one got stuck just like you see in the screenshots. 
Failed in master

**Comment by Almansherov** [comment]
Successfully uninstalled libvirt
Fixed

**Comment by kurmanbekova6** [comment]
Successfully uninstalled libvirt
![screenshot from 2018-11-14 14-52-26](https://user-images.githubusercontent.com/9501291/48470897-eb58e500-e81c-11e8-857d-668d6eb5a7c3.png)
Tested in prod

**Comment by kurmanbekova6** [comment]
![screenshot from 2018-11-14 14-52-26](https://user-images.githubusercontent.com/9501291/48470958-07f51d00-e81d-11e8-8806-59b971260b23.png)
