### ISSUE TITLE
Add pre-installation checklist KVM

### ISSUE THREAD

**Issue by jadilet** [subutai-io/control-center#1727]
Add Check CPU supports hardware virtualization while installing the KVM.

**Comment by Almansherov** [comment]
If the result is positive number, it means the machine supports CPU check:

![image](https://user-images.githubusercontent.com/32430693/47898037-19641f80-de42-11e8-8a98-b36169413a41.png)

Fixed in master

**Comment by kurmanbekova6** [comment]
Tested in prod.
![screenshot from 2018-11-14 14-18-32](https://user-images.githubusercontent.com/9501291/48469251-84d1c800-e818-11e8-8edb-1d825c01acef.png)
