### ISSUE TITLE
Control Center crashing during  ssh key removal on Mac OS [Master]

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1731]
**How to reproduce:**

- Go to ssh-keys management.
- From existing keys delete one of the keys.  (you should have more than  2 keys.)
- Delete the second one.

_Result: CC will crash._

[logs_18.txt](https://github.com/subutai-io/control-center/files/2487435/logs_18.txt)

**Comment by kurmanbekova6** [comment]
This situation exists on Ubuntu too
[logs_10.txt](https://github.com/subutai-io/control-center/files/2532753/logs_10.txt)
[logs_11.txt](https://github.com/subutai-io/control-center/files/2532754/logs_11.txt)
on Ubuntu

**Comment by Almansherov** [comment]
When I removed the second key, cc crashed.
Failed in master

**Comment by Almansherov** [comment]
Forgot to update the cc. 
Tested one more time.
Fixed in master

**Comment by kurmanbekova6** [comment]
Removed several keys, CC did not crash.  Tested in prod
