### ISSUE TITLE
СС  should allow to create a new password after bringing a peer up.

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1732]
Currently after implementation of providers, we can manage peers which were brought up using vagrant providers on CC (Manually). But after bringing up a peer using vagrant providers, we cannot register them to Bazaar. 
First, we should go to Subutai Console, change password, and after that we can manage peer on Control Center.

**How to reproduce:**

-  Bring a peer up using vagrant providers.
- https://github.com/subutai-io/vagrant/wiki/How-to-Install-and-Use-Vagrant-Providers
- Try to register the peer on Bazaar via Control Center.

*Result:*
You cannot register peer, because first you need to change peer's password in order to succeed.

**Expected behavior:**
Would be better, if CC would add `change password` possibility like Subutai Console.

![screenshot from 2018-10-17 12-51-54](https://user-images.githubusercontent.com/9501291/47101972-51be0800-d25d-11e8-9e08-9ed4e044821d.png)

**Comment by Almansherov** [comment]
This feature will not be available in the current cc. Would be good to have it in subutron
