### ISSUE TITLE
Facilitate the installation of VMware Workstation on Linux.

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1733]
Currently  installation of  VMware Workstation uses security privileges to launch.

**How to reproduce:**

- - Install all needed components for VMWare Workstation.
- - Open VMware Workstation and select trial period. It will ask you root password. Even root password is correct, you can not pass. 
- - You need to run it:
`sudo su`
`vmware`
- - After this you can open VMware Workstation.

**Comment by crioto** [comment]
This is a known issue in VMWare Workstation. Here is the reference: https://communities.vmware.com/thread/481396
We will try to workaround/fix in control-center, but there is no any guarantees, that it will work.

**Comment by crioto** [comment]
This is the problem of VMWare on Ubuntu, related to obscured `root` user on Ubuntu OS: https://communities.vmware.com/thread/155402
