### ISSUE TITLE
Control Center crashing when user has a lot of environments. [Master CC]

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1734]
**How to reproduce:**

- Create a lot of environments (via parallel environment creation script)
- Login to CC.
- Go to your environments.

_Result: CC will crash_

**Comment by Almansherov** [comment]
Logs from my machine. Faced a crash as well. Debian. Master:

[logs_05.zip](https://github.com/subutai-io/control-center/files/2491511/logs_05.zip)

**Comment by kurmanbekova6** [comment]
Left Control Center with 60 environments for the night.
Control Center did not crash.
Fixed in Master

**Comment by kurmanbekova6** [comment]
Did not face on prod.
