### ISSUE TITLE
CC doesn't know if a peer should be updated 

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1735]
_Master Control Center_
_Debian_
Summary:
I have started my old peer. It successfully has had a `RUNNING` state in CC. I thought about updating it, but cc said `No Updates available`:

![image](https://user-images.githubusercontent.com/32430693/47147630-476b3080-d294-11e8-86fd-84ee4d7b4d8c.png)

So, I registered it to masterbazaar and wanted to start using it. But bazaar says that my peer has incompatible version:

![image](https://user-images.githubusercontent.com/32430693/47147668-5c47c400-d294-11e8-8e49-3c488b0e1522.png)

I think peer update function is broken in cc. 

Logs:

[logs_05.zip](https://github.com/subutai-io/control-center/files/2491378/logs_05.zip)

I will keep this peer not updated, in case if it can be needed

**Comment by jadilet** [comment]
Can you check does peer os show update (`System/Updates`)?

**Comment by Almansherov** [comment]
@jadilet yes, peer os says that there is an update available:

![image](https://user-images.githubusercontent.com/32430693/47149361-fc075100-d298-11e8-9aaf-63b682cc0147.png)

**Comment by jadilet** [comment]
I was not able to reproduce.

**Comment by Almansherov** [comment]
Was not able to reproduce.
Will be monitoring this issue

**Comment by Almansherov** [comment]
Nope, Didn't face this issue

Fixed
