### ISSUE TITLE
Control Center shows wrong path in file transfer.

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1737]
**Steps to reproduce:**

- Create environment. 
- Go to transfer file.
- Click to one folder several times.

Result: Control Center will show incorrect path.

![screenshot from 2018-10-22 11-17-44](https://user-images.githubusercontent.com/9501291/47334493-d9b27080-d6a8-11e8-867f-62bc4322c7a9.png)

**Comment by Almansherov** [comment]
here is the screenshot:

![image](https://user-images.githubusercontent.com/32430693/47424624-a83fb080-d74d-11e8-8c53-617a5371152e.png)

**Comment by Almansherov** [comment]
Fixed in master

**Comment by Almansherov** [comment]
Double clicked on a directory and it got into the directory twice:

![image 2](https://user-images.githubusercontent.com/32430693/51169027-70d63100-1870-11e9-80b9-4a9cea3120d6.png)

Failed in master

**Comment by Almansherov** [comment]
Fixed in master:

![image](https://user-images.githubusercontent.com/32430693/51991152-252aa680-2470-11e9-98e5-68409cc8ad0d.png)
