### ISSUE TITLE
Install button's color should be like other components.

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1750]
**Steps to reproduce:**

- Delete Control Center's components.

Result: X2Go-Client's install button is blue. 

P.S. The cursor is not over the button.

<img width="629" alt="screen shot 2018-10-24 at 11 18 22 am" src="https://user-images.githubusercontent.com/9501291/47422060-a43e7d80-d7a3-11e8-92e3-ee2e99cca15b.png">

**Comment by jadilet** [comment]
I wasn't able to reproduce this issue with latest master CC.

**Comment by kurmanbekova6** [comment]
![screenshot from 2018-11-14 14-39-50](https://user-images.githubusercontent.com/9501291/48470314-4689d800-e81b-11e8-8702-991bc494586b.png)
Tested in prod
