### ISSUE TITLE
Remote directory failing with reason: Failed  to refresh remote directory.

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1753]
**Steps to reproduce:**

- Go to environments.
- Click transfer file.

<img width="906" alt="screen shot 2018-10-24 at 6 11 42 pm" src="https://user-images.githubusercontent.com/9501291/47429606-b840aa00-d7b8-11e8-8c9c-3c4957eec74f.png">

**Comment by jadilet** [comment]
Please check the p2p and ssh to the container are working. 
Please post the logs.

**Comment by Almansherov** [comment]
Fixed in master:

![screenshot from 2018-11-01 18-05-33](https://user-images.githubusercontent.com/32430693/47894739-6d670800-de32-11e8-8234-1d35ec3d233b.png)

**Comment by kurmanbekova6** [comment]
![screenshot from 2018-11-14 14-36-05](https://user-images.githubusercontent.com/9501291/48470086-b2b80c00-e81a-11e8-9b52-a987dde6997b.png)
Tested in prod
