### ISSUE TITLE
Can't delete Virtual Box via Control Center

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1754]
**Steps to reproduce:**

- Install CC's components
- Try to delete Virtual Box

_Result:_ 
If you will try to delete, you will face error below: 
![screen shot 2018-10-24 at 21 35 30](https://user-images.githubusercontent.com/9501291/47477026-eff53380-d844-11e8-8a84-dcdd1ac5a889.png)
Virtual Box's checkbox  will be  checked. You can uncheck it. It will occur when you try to delete second time.
![screen shot 2018-10-24 at 21 35 20](https://user-images.githubusercontent.com/9501291/47477150-97726600-d845-11e8-99f4-7b7c03d4de60.png)

![screen shot 2018-10-24 at 21 38 15](https://user-images.githubusercontent.com/9501291/47477030-f2578d80-d844-11e8-9753-e6b4dd442e24.png)

**Comment by jadilet** [comment]
`VirtualBox_Uninstall.tool`  file not uploaded to the Bazaar cdn.
Team infra will upload this file.

**Comment by jadilet** [comment]
@kurmanbekova6 We uploaded the missing file(`VirtualBox_Uninstall.tool`). Can you check?

**Comment by Almansherov** [comment]
Successfully uninstalled and installed Virtual Box on MacOS and Debian.

Fixed in prod

**Comment by kurmanbekova6** [comment]
Tested in prod.
![screen shot 2018-11-14 at 14 43 34](https://user-images.githubusercontent.com/9501291/48470470-b6985e00-e81b-11e8-9817-447342e7c4dd.png)
