### ISSUE TITLE
Update whole Subutai instead of Subutai P2P on desktop peers.

### ISSUE THREAD

**Issue by amangeldizhusubaliev** [subutai-io/control-center#1757]
## Expected Behavior

Updating P2P must work correctly on desktop peers

## Current Behavior

Updating P2P via CC on desktop peers leads to removal of Subutai which kills this peer.

## Possible Solution

Update whole Subutai instead of Subutai P2P on desktop peers. Use `subutai update rh`.

## Steps to Reproduce

1. Create desktop peer.
2. Try to update or uninstall P2P via CC
You will end up with broken peer.

**Comment by jadilet** [comment]
The p2p update fixed on the desktop peer.
