### ISSUE TITLE
Broken peer registration with very strange HTTPS cert error

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/control-center#1768]
Peer registration is broken and we get this strange error.

![image](https://user-images.githubusercontent.com/10051386/47605576-12d44300-da11-11e8-9e0d-fb6fea5bfb1c.png)

I think this is due to the bazaar certificate for some reason. I cannot understand why this is happening. Included @tasankulov and @etursunbaev to assist.

**Comment by akarasulu** [comment]
I can also give access to this machine to troubleshoot.

**Comment by akarasulu** [comment]
https://optdyn.slack.com/archives/C8B3WAQD7/p1540636902008900

**Comment by akarasulu** [comment]
Seems @kurmanbekova6 seems to have [found this same issue](https://optdyn.slack.com/archives/C76FFHJRH/p1540367602000100) and @Dilshat you called it a network issues and moved on. Let's not ignore QA please.

**Comment by etursunbaev** [comment]
@akarasulu on @kurmanbekova6 issue we solved with changing timezone. But couldn't reproduce again.
Can you set right UTC timezone, than restart peer. Might be the same symptoms.

**Comment by etursunbaev** [comment]
This issue is resolved by changing/fixing timezone on host machine on client side.

**Comment by Almansherov** [comment]
So, the issue is not related to CC
