### ISSUE TITLE
Silly naming of SSH keys

### ISSUE THREAD

**Issue by lbthomsen** [subutai-io/control-center#1769]
I do think it's a CC problem.  In Bazaar each key has got a name and content - you can name is as you like.  My key on my laptop looks like:
```ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVr6/DgKBDYDTIycoghhoTT27aEfsdjvQrb1V5D9MHeqRoquh2Zp16rgkhKzr90jctiSNkdZLIVJ+L4nGMoPx1q2TF01qop/NwEK/JkbaEuWbch72hCHrQXcukxFw2yo9uPFrYENFWXj2CWlSQYoZc9WOSKXNzpVVHxjeD1NcvjXKOK5qa8oAZ7q0AzbhWUKhOZqvxjnrZXbIhI+prlcGUZNhW7/SGLmGQ7xIp3VPYr+At9VzlBiR3Qvh9k6gy7scYprfgWbrhDvGqN/MAmYy6IyX15Wi7CNBotFpF1UYIg/U/8rFFryQdQ3S3m9HD0CRp42fUjmM2ckbkWDsPsNoh lth@nb7```
The problem is that CC names this id_rsa.pub on Bazaar which is insane since that is what it is called on every single Unix machine.  It would have been much better if it was uploaded as `lth@nb7` - information which could be fetched from the key itself.  That would solve the issue.  This was what I suggested back in July and as I mentioned then I am quite concern that this changed at some point.

**Comment by akarasulu** [comment]
[Discussion thread from chat](https://optdyn.slack.com/archives/C76FFHJRH/p1540686090193800)

**Comment by Almansherov** [comment]
Followed the test steps above^
ssh keys with the same name on different computers:

![image](https://user-images.githubusercontent.com/32430693/48176338-2e72ff80-e2d5-11e8-9d57-4f2126008497.png)

fixed in master

**Comment by kurmanbekova6** [comment]
Tested in prod
![screenshot_17](https://user-images.githubusercontent.com/9501291/48468671-bd70a200-e816-11e8-9b07-c599416dd546.png)
