### ISSUE TITLE
Question mark in Components

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1776]
When I reinstalled Vagrant in cc  on MacOs. When the installation was finished , the question mark appeared in Components. See the screenshot: 

<img width="602" alt="screen shot 2018-11-01 at 10 15 34 am" src="https://user-images.githubusercontent.com/32430693/47834596-1ac41800-dd6e-11e8-9724-f38cdfcda634.png">

Here are the latest logs:

[logs_18.zip](https://github.com/subutai-io/control-center/files/2537322/logs_18.zip)

Steps are simple:

Just delete Vagrant and install it again.

**Comment by kurmanbekova6** [comment]
Reintalled Vagrant via CC.
When the installation was finished, did not get question mark on Vagrant.
Question mark on other components disappeared right after I checked for updates
<img width="619" alt="screen shot 2018-12-06 at 12 25 59 pm" src="https://user-images.githubusercontent.com/9501291/49565692-41b7d000-f952-11e8-8058-508a5b18818c.png">

**Comment by kurmanbekova6** [comment]
<img width="601" alt="screen shot 2018-12-06 at 11 17 47 am" src="https://user-images.githubusercontent.com/9501291/49567110-023fb280-f957-11e8-8479-9852796c8cdf.png">

**Comment by kurmanbekova6** [comment]
Expected behavior:
After installation of components, there should not be question mark and null
Failed in master

**Comment by kurmanbekova6** [comment]
Faced with question mark only below case:
Reinstalled Vagrant. 
<img width="628" alt="screen shot 2018-12-07 at 5 45 47 pm" src="https://user-images.githubusercontent.com/9501291/49646069-3d6dde80-fa48-11e8-9988-d248d045e927.png">
Question mark on other components disappeared right after I checked for updates

**Comment by kurmanbekova6** [comment]
Tested in master

**Comment by Almansherov** [comment]
Fixed in prod
