### ISSUE TITLE
An invisible Control Center's window on the Ubuntu desktop

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1786]
In the foreground of Ubuntu desktop, there is invisible CC's window. 
Could not close window until quit the CC.

**Steps to reproduce:** 
![screenshot from 2018-11-05 18-14-02](https://user-images.githubusercontent.com/9501291/47998511-c3d19080-e129-11e8-89a0-40d9031c50e3.png)

**Comment by Almansherov** [comment]
We will be monitoring this issue. Moving it to the other pipeline

**Comment by Almansherov** [comment]
Have not faced this issue.
Failed to reproduce
