### ISSUE TITLE
Firefox install/uninstall functions

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1789]
The logic of firefox installation seems to be wrong.
When a user wants to install it, she/he faces the error about failed installation:

![image](https://user-images.githubusercontent.com/32430693/48051430-b38dd580-e16a-11e8-9ae6-490204230eab.png)

But Components windows shows firefox installed

And when a user wants to uninstall it, the notification claims that it is successfully uninstalled, but Components windows is stuck:

![image](https://user-images.githubusercontent.com/32430693/48051554-0ebfc800-e16b-11e8-8e6c-5b10274323da.png)

Steps to reproduce:
1. Install Firefox and monitor the notifications and Components window
2. Uninstall Firefox and monitor the notifications and Components window

Expected behavior:
The behavior of Notifications and Components should match.  
Logs:

[logs_22.txt](https://github.com/subutai-io/control-center/files/2552193/logs_22.txt)
[notifications-master.log](https://github.com/subutai-io/control-center/files/2552197/notifications-master.log)

**Comment by Almansherov** [comment]
It says `Uninstalled`, but the progress bar is stuck:

![image](https://user-images.githubusercontent.com/32430693/49505667-df6faa00-f841-11e8-8f94-b4be9f005988.png)

Failed in master

**Comment by kurmanbekova6** [comment]
![screenshot from 2018-12-10 15-13-28](https://user-images.githubusercontent.com/9501291/49722138-320bf480-fc8e-11e8-9503-a703a0a47e59.png)
Tested in master

**Comment by kurmanbekova6** [comment]
Successfully reinstalled firefox via CC.
Tested in prod.
