### ISSUE TITLE
CC shows peer's status wrong on Linux. 

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1792]
**Steps to reproduce:**
Bring peer up via Libvirt.
After creation close the terminal.
CC will show peer's status wrong.

Once we close the terminal peer's status will change to `not ready`
![screenshot from 2018-11-07 17-05-17](https://user-images.githubusercontent.com/9501291/48128290-33718800-e2b0-11e8-8c25-506c2003ba93.png)

**Comment by kurmanbekova6** [comment]
Installed latest vagrant subutai plugin.
Successfully brought up peer via Libvirt.
Closed terminal.
Peer's status `ready`.
![screenshot from 2018-11-09 16-08-45](https://user-images.githubusercontent.com/9501291/48256540-2aacbd80-e43a-11e8-8830-d7747d9defed.png)
Tested in master.

**Comment by Almansherov** [comment]
After the hotfix now peers connections are stable due to using IP of peer.
Fixed
