### ISSUE TITLE
[osx] the script in the terminal should be hidden

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1793]
in the following screenshot you can see the script in terminal:

![image](https://user-images.githubusercontent.com/32430693/48178614-3a17f380-e2e0-11e8-837d-f58e8098c746.png)

Ideally, it should be hidden. 

Steps to reproduce: 
Create a peer using parallels provider
check the terminal while creation
get into the directory where it is located and run commands asking peer information

**Comment by kurmanbekova6** [comment]
<img width="1128" alt="screen shot 2018-12-06 at 12 13 16 pm" src="https://user-images.githubusercontent.com/9501291/49566630-8729cc80-f955-11e8-9e1a-75ba9dddebcb.png">
Did not get any script while deleting in terminal

**Comment by Almansherov** [comment]
Fixed in master

**Comment by kurmanbekova6** [comment]
<img width="541" alt="screen shot 2019-01-02 at 11 16 15 am" src="https://user-images.githubusercontent.com/9501291/50581068-2623e480-0e80-11e9-8d32-343f8c0d3927.png">
Tested in prod.
