### ISSUE TITLE
CC should clean peer directory after destroying the peer

### ISSUE THREAD

**Issue by jadilet** [subutai-io/control-center#1814]
## Expected Behavior

CC should clean the peer directory after destroying the peer.
## Current Behavior

After destroying the peer still, exist the peer directory.

**Comment by jadilet** [comment]
How to:
create a directory in peers folder with a name `subutai-peer_existpeerbek`
then create a peer via cc with the same name
Result: CC will check if there is a peer in the directory and if not, it will start the creation process.

**Comment by Almansherov** [comment]
Followed the steps above^

CC started the peer creation process inside of the directory:

![image](https://user-images.githubusercontent.com/32430693/50443534-71128a80-08c9-11e9-91f3-43e89ec6468d.png)

Fixed in master
