### ISSUE TITLE
Peers are disappearing from Control Center

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1821]
**Steps to reproduce:**

- Create peer.
- Wait some time and check your peer/ The peer may disappear during bringing up.

**Result:**
<img width="354" alt="screen shot 2018-12-07 at 4 57 17 pm" src="https://user-images.githubusercontent.com/9501291/49644421-9aff2c80-fa42-11e8-8aea-b58faae3bc03.png">
**Actually:**
After restarting CC
<img width="324" alt="screen shot 2018-12-07 at 5 07 53 pm" src="https://user-images.githubusercontent.com/9501291/49644838-ed8d1880-fa43-11e8-8188-18324d22ed76.png">

[logs_14.txt](https://github.com/subutai-io/control-center/files/2656986/logs_14.txt)
[logs_16.txt](https://github.com/subutai-io/control-center/files/2656987/logs_16.txt)

**Comment by kurmanbekova6** [comment]
![1](https://user-images.githubusercontent.com/9501291/49644914-38a72b80-fa44-11e8-8e7b-7fa4d3336401.png)
![2](https://user-images.githubusercontent.com/9501291/49644917-3a70ef00-fa44-11e8-933b-89813d1de6e0.png)

**Comment by kurmanbekova6** [comment]
Peers are did not disappear
![screenshot from 2018-12-10 15-58-33](https://user-images.githubusercontent.com/9501291/49724829-7601f800-fc94-11e8-9a3a-8d0c9c3b8e41.png)

**Comment by Almansherov** [comment]
On debian machine cc doesn't see the peers that I have in my machine:

![screenshot from 2018-12-10 22-49-51](https://user-images.githubusercontent.com/32430693/49779112-ed07b280-fccd-11e8-99b0-6273a9c61663.png)

failed in stage

**Comment by Almansherov** [comment]
Created the peers with different providers, checked their states, and cc showed me everything.
Was not reproduced.
Fixed in master

**Comment by kurmanbekova6** [comment]
Did not face with it.
Tested in prod.
