### ISSUE TITLE
 When user turns off peer, peer getting doubled.

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1822]
**Steps to reproduce:**
Just turn off registered peer.

![screenshot from 2018-12-07 16-17-59](https://user-images.githubusercontent.com/9501291/49645033-a0f60d00-fa44-11e8-81f9-7ddb6e63946f.png)

![screenshot from 2018-12-07 17-26-33](https://user-images.githubusercontent.com/9501291/49645229-44dfb880-fa45-11e8-91bb-6da1a01ad19c.png)

**Comment by kurmanbekova6** [comment]
Test1 and Libvirt are in my machine.
![screenshot from 2018-12-10 15-02-11](https://user-images.githubusercontent.com/9501291/49721616-ead13400-fc8c-11e8-9369-062254aee7ab.png)
![screenshot from 2018-12-10 15-04-55](https://user-images.githubusercontent.com/9501291/49721641-f91f5000-fc8c-11e8-9e46-eae516bf4b31.png)
Failed in master

**Comment by kurmanbekova6** [comment]
Here is another example:
![screenshot from 2018-12-10 15-41-26](https://user-images.githubusercontent.com/9501291/49723859-1f93ba00-fc92-11e8-8424-4d03e8699888.png)
Brouht two peers up. Turned them off.
Result:
Peer `Disapp` get doubled.

**Comment by Almansherov** [comment]
Stopped and started again the peers with different providers
Fixed in master

**Comment by kurmanbekova6** [comment]
Could not reproduce on prod.
Peers did not get doubled.
Tested in prod.
