### ISSUE TITLE
Can not register a peer on Mac

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1823]
**In my case:**

- Brought a peer up via VMWare Fusion.
- Turned off and turned on it again.
- Tried to register the peer.

[logs_17.txt](https://github.com/subutai-io/control-center/files/2657069/logs_17.txt)

**Comment by kurmanbekova6** [comment]
Registered successfully several times

**Comment by etursunbaev** [comment]
It is duplication of https://github.com/subutai-io/control-center/issues/1768
and time zone difference on host causes this issue.
@Almansherov let's close
