### ISSUE TITLE
СС displaying destroyed peer

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1832]
**Steps to reproduce:**

- Destroy running peer

**Result:**
_Peer will be deleted from second attempt_
<img width="372" alt="screen shot 2018-12-13 at 10 27 05 am" src="https://user-images.githubusercontent.com/9501291/49936930-6f2aed80-feff-11e8-8f98-e11595705b5e.png">

**Comment by Almansherov** [comment]
Successfully deleted a peer and checked it in the list:

![image](https://user-images.githubusercontent.com/32430693/50000662-d5dff380-ff5f-11e8-8021-dcc9e27609e5.png)

Fixed in master

**Comment by Almansherov** [comment]
Destroyed bunch of peers and checked the list of my peers in cc.
No bug was faced.
Fixed in prod
