### ISSUE TITLE
Cannot uninstall Chrome and Browser plugin from CC

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1833]
Uninstall all the components and try to install them again.

As a result, Chtome and Browser plugins cannot be uninstalled:

<img width="620" alt="screen shot 2018-12-14 at 5 36 37 pm" src="https://user-images.githubusercontent.com/32430693/50001419-6b7c8280-ff62-11e8-8264-16a147d0bf36.png">

**Comment by Almansherov** [comment]
Successfully installed/uninstalled all the components

**Comment by kurmanbekova6** [comment]
Successfully reinstalled Chrome via CC.
Tested in prod.
