### ISSUE TITLE
Don't reload ControlCenter if other updates are running

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/control-center#1837]
In "Components" I see that update is available for CC, P2P, Vagrant Subutai box and plug-in. 
First I started to update Vagrant box and plug-in, then in the middle of them clicked to update CC and P2P. 
In result, CC asked me that it needs to reload to update CC (other updates are still running), I clicked "Reload".

Result: other updates interrupted.

Expected behavior: CC must not reload until other updates finished.

**Comment by Almansherov** [comment]
Now cc blocks the update of cc if there is a process going behind the command:

![image](https://user-images.githubusercontent.com/32430693/50475150-44be4300-0989-11e9-94cc-09dd1edc0433.png)

Fixed in master

**Comment by Almansherov** [comment]
<img width="725" alt="screen shot 2018-12-27 at 3 47 34 pm" src="https://user-images.githubusercontent.com/32430693/50475456-708df880-098a-11e9-9c0d-0cb31beab2f0.png">
