### ISSUE TITLE
CC consuming more memory RAM by the time

### ISSUE THREAD

**Issue by jadilet** [subutai-io/control-center#1839]
## Expected Behavior

Creating and destroying threads frequently can be expensive. To avoid the cost of thread creation, I will use a thread pool. [Heredocs](http://doc.qt.io/qt-5/qthreadpool.html) of the thread pool.

## Current Behavior

CC creates a new thread and destroys thread for getting peer list and checking peer status.

**Comment by jadilet** [comment]
This [issue](https://github.com/subutai-io/control-center/issues/1770) might be related to this. After Quit the CC(ControlCenter), CC not deleting background thread.

**Comment by Almansherov** [comment]
CC has been running since Monday (Today is thursday, so during three days cc eats up to 200 mb):

![image](https://user-images.githubusercontent.com/32430693/51655058-8c23f900-1f60-11e9-8f0a-2035417f6ba3.png)

Debian Linux.
