### ISSUE TITLE
Add new ssh command to cc CLI

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1864]
Summary: So, the user should be able to ssh into a container.

Something like that:
`SubutaiControlCenter --ssh env_name:cont_name`

**Comment by jadilet** [comment]
How to test:
First, launch the SubutaiControlCenter.
Second, do the following command for ssh to a container via SubutaiControlCenter command.
 Windows:
    * launch cmd as administrator privileges
    * `SubutaiControlCenter.exe --ssh env_name:cont_name`

Mac and Linux:
   * `SubutaiControlCenter --ssh env_name:cont_name`

**Comment by kurmanbekova6** [comment]
Windows
![screenshot_18](https://user-images.githubusercontent.com/9501291/51671898-53cdfa80-1ff4-11e9-8566-a5e987a93bb1.png)

**Comment by kurmanbekova6** [comment]
Linux:
![screenshot from 2019-01-24 16-33-19](https://user-images.githubusercontent.com/9501291/51672476-ca1f2c80-1ff5-11e9-904e-45dfa07a4c6a.png)
