### ISSUE TITLE
Chrome Installation Failure

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1872]
Windows. master. 
If user wants to install chrome, he/she faces the following error:

![image](https://user-images.githubusercontent.com/32430693/51330451-6365a600-1a2c-11e9-94d6-a15543309627.png)
So, I suppose rest api of masterbazaar is broken?

**Comment by jadilet** [comment]
The chrome installation file uploaded to CDN.

**Comment by kurmanbekova6** [comment]
Successfully installed Chrome. Did not get above error.
