### ISSUE TITLE
vms0-bare peer located on the same host ... well not seen as a local peer

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1873]
How to:
* Create a peer 
* Compare the lists `My Peers` and `LAN peers

As a result, the peer that was brought up in the same LAN will not be listed.

![image](https://user-images.githubusercontent.com/32430693/51334338-77ada100-1a34-11e9-9f7f-8b307de77fd8.png)

**Comment by Almansherov** [comment]
My Peers:

![image](https://user-images.githubusercontent.com/32430693/52110080-27eae000-25c5-11e9-88aa-47960696efb5.png)

LAN peers:

![image](https://user-images.githubusercontent.com/32430693/52110112-3a651980-25c5-11e9-8539-58a9015aadc0.png)

**Comment by jadilet** [comment]
The CC only can manage the vagrant peers. We should hide this message.

**Comment by Almansherov** [comment]
Fixed in master:

![Uploading image.png…]()
