### ISSUE TITLE
Providers switch

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1877]
Alex's comment in public channel: 
`Whenever users switch from different hypervisors some commands will need to be run to actually switch between some that might be incompatible together. This occurs with some hypervisors on some OS'. Just as an example you can see what needs to be done to allow Linux to switch between vbox and kvm -- one article here https://www.dedoimedo.com/computers/kvm-virtualbox.html
Without these things being done yes we will have severe errors and things will break users will say this does not work.`

**Comment by jadilet** [comment]
How to test:
If we change the vagrant provider from the settings, the CC checks running peer and gives the message to turn off the peer.

**Comment by Almansherov** [comment]
Successfully turn the peers off:

![image](https://user-images.githubusercontent.com/32430693/51828515-5a3cca80-22b1-11e9-9293-4c68c8b7046c.png)
