### ISSUE TITLE
Peer was successfully created, but status is wrong [master]

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1883]
Steps to reproduce:
Bring peer up via Parallels
<img width="609" alt="screen shot 2019-01-24 at 3 21 02 pm" src="https://user-images.githubusercontent.com/9501291/51670634-44997d80-1ff1-11e9-906e-e23d47c63642.png">
P.S. Reloaded twice, but did not help

**Comment by kurmanbekova6** [comment]
Here another one:

![screenshot_9](https://user-images.githubusercontent.com/9501291/51741998-a4ac2480-20c2-11e9-9569-ab670993aa30.png)
![screenshot_10](https://user-images.githubusercontent.com/9501291/51742002-a83fab80-20c2-11e9-9148-c079238499af.png)

**Comment by jadilet** [comment]
This is a sysnet issue, I have reported this issue.

**Comment by Almansherov** [comment]
So, if this issue does not belong to cc, it is closed
