### ISSUE TITLE
Can't install vagrant subutai box on Mac OS

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1895]
Steps to reproduce:
Use VMWare Fusion
Install vagrant subutai box
![screenshot 2019-02-04_09-06-03-854](https://user-images.githubusercontent.com/9501291/52188296-4d454b80-285c-11e9-858f-1b9ee0131898.png)

**Comment by jadilet** [comment]
`File download error. Connection closed`
This is network issue. Please try again.

**Comment by Almansherov** [comment]
Successfully started the subutai box installation on windows:

![box1](https://user-images.githubusercontent.com/32430693/52193505-10099b00-2815-11e9-8f53-b6603d25844d.png)

**Comment by Almansherov** [comment]
Done:
![box3](https://user-images.githubusercontent.com/32430693/52193587-80b0b780-2815-11e9-9a9d-a80e5305fca7.png)

**Comment by Almansherov** [comment]
Successfully installed on Linux:

![image](https://user-images.githubusercontent.com/32430693/52193797-7e029200-2816-11e9-9c60-58bd8393c82e.png)
