### ISSUE TITLE
After turning on Hyper-V and restarting machine, hyper-v cuts off the internet.

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1896]
**Steps to reproduce:**

- Enable Hyper-V.
- Restart the machine.

![screenshot_4](https://user-images.githubusercontent.com/9501291/52190627-563d1980-286a-11e9-8133-0b63b8530f24.png)

**Comment by jadilet** [comment]
Th Hyper-V changes the network interface while disabling or enabling. This can't be handled by the CC.
