### ISSUE TITLE
Continued problems with CDN CC update detection via Components Dialog

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/control-center#1916]
The Components Dialog (CD) keeps showing the availability of Control Center (CC) itself even if at the latest version across all operating systems. This was tested with the latest installers for respective operating systems from the Subutai Website Downloads links. Each OS seems to be behaving slightly different as outlined below.

## Expected Behavior
Upon downloading and installing the latest Subutai Control Center from the Subutai Website download links for respective OSs we should not see the CD showing any available updates for CC.

### Windows

There are two noticeable problems:

1. The version of CC is incorrect at 7.3.6, which should be 7.3.7
2. There is an available update with an active `Update` button for CC in CD

<img width="350" alt="Screen Shot 2020-03-15 at 4 18 00 AM" src="https://user-images.githubusercontent.com/10051386/76691329-fbccda00-6673-11ea-9b5a-41f9f521fc6e.png">

### Mac OS X

The expected version is 7.3.7 however there is an available update with an active  `Update` button for CC in CD.

<img width="632" alt="Screen Shot 2020-03-15 at 4 18 53 AM" src="https://user-images.githubusercontent.com/10051386/76691340-1a32d580-6674-11ea-8fd7-8031a457dc7e.png">

### Linux

The expected version is 7.3.7 however there is an available update with an inactive `Update` button for CC in CD. It is probably the same problem as with Mac OS X in terms of falsely detecting an available update however the UI is just making the button inactive instead of active. If working properly it should have nothing at all next to the CC component: unlike other components having checkboxes to uninstall CC does not provide it since uninstalling it makes everything else uninstallable for the Subutai System.

<img width="625" alt="Screen Shot 2020-03-15 at 4 28 54 AM" src="https://user-images.githubusercontent.com/10051386/76691501-819d5500-6675-11ea-9296-e359c8ea9525.png">

## Possible Solution
The work done in the past to solve this problem seems to not be working. We need to revisit what's going on especially with the build system and how it drops builds into the CDN and make the appropriate changes in the CC code that detects the availability of CC updates.

## Steps to Reproduce

1. Install CC onto a fresh system (any OS) and goto the Components Dialog.
2. Press the button to check for updates if it does not begin to do so automatically.

## Context (Environment)
All desktop operating systems show this annoying problem which misleads users into thinking they do not have the most up to date version of Subutai CC. There's a general loss of confidence in the software working properly.

I have yet to try to see what updates actually do. I will report that in another separate issue post.

**Comment by crioto** [comment]
This issue have been resolved in 7.3.9
