### ISSUE TITLE
Localization - Russian

### ISSUE THREAD

**Issue by Lezh1k** [subutai-io/control-center#222]
We can use qt internal mechanism or make own (xml based, for example) .

**Comment by akarasulu** [comment]
xml based translation files ?

**Comment by Lezh1k** [comment]
```
<menu_about>
  <en>about</en>
  <ru>о программе</ru>
  <ch>O programu</ch>
</menu_about> 
```
For example. Or use king of table.

**Comment by akarasulu** [comment]
got you @Lezh1k

**Comment by Lezh1k** [comment]
Added russian translate.

**Comment by Lezh1k** [comment]
Instruction : 
1. Clone tray (git clone) 
2. Switch to dev branch (git checkout dev) 
3. Update (git pull origin dev)
4. Use file SubutaiTray_pt_BR.ts 
5. %1, %2 etc are placeholders, so don't change it. 
6.  
```
 <message>
        <location filename="hub/src/updater/UpdaterComponentTray.cpp" line="87"/>
        <source>Tray application has been updated. Do you want to restart it now?</source>
        <translation>BRAZILIAN TRANSLATE</translation>
    </message>

```
7. Move all changes to new br_translate branch (git checkout -B br_translate)
8. Commit and push changes
9. Create pull request to dev branch

**Comment by efeefe** [comment]
Moving the portuguese version to another issue.

**Comment by amol4anoff** [comment]
Not fully translated:

<img width="711" alt="screenshot at feb 02 14-50-54" src="https://user-images.githubusercontent.com/33647491/35724744-102e0236-0829-11e8-8ff1-9522755cc423.png">


We need to pick one - Окружения or Инфраструктуры.
IMHO - Инфраструктуры is better, more technological.

<img width="676" alt="screenshot at feb 02 14-52-19" src="https://user-images.githubusercontent.com/33647491/35724841-6b2b96da-0829-11e8-91a0-86f226fa2f20.png">

<img width="267" alt="screen shot 2018-02-02 at 2 52 31 pm" src="https://user-images.githubusercontent.com/33647491/35724855-73eadf88-0829-11e8-9147-5558e7a61591.png">

**Comment by amol4anoff** [comment]
Please finish, so we will be able to check.

**Comment by amol4anoff** [comment]
@Erkin97 please make new phrases to be translated, so @ibragim13kz will be able to finish.

**Comment by ibragim13kz** [comment]
Done.

**Comment by ibragim13kz** [comment]
Can not close because this is a long term issue, so we need to update it periodically.

**Comment by Almansherov** [comment]
Not relevant anymore
