### ISSUE TITLE
[Spike] Implement notifications for user Hub events

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/control-center#229]
- Balance changes
- User coming onto your peer
- Getting a message from Hub users in chat

Figure out what's needed for this and make a plan. We will only do this if we have enough time and most likely push it to 5.0.3.

**Comment by Lezh1k** [comment]
Need REST points for 2 and 3. 
For 3 is better to use websockets, but it's more HUB related thing I guess

**Comment by akarasulu** [comment]
@Lezh1k If we do use web sockets then we should just be given event notifications as messages. These events will then trigger reads from REST endpoints. Doesn't that consume a socket per client though?

**Comment by akarasulu** [comment]
I moved this to 5.0.3 release because we do not have time for this.

**Comment by Almansherov** [comment]
Chat of bazaar does not work in order to implement this feature from cc side
