### ISSUE TITLE
[Linux] [ud1704] EZ-SSH into peers on same LAN fails 

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/control-center#257]
This might be a combined p2p and tray problem. I can EZ-SSH into all containers minus ones on the same LAN in an xpeer environment spanning cloud peers across continents. This requires more experimentation and feedback before anyone spends too much time chasing this bug. However, it's serious.

**Comment by amol4anoff** [comment]
Didn't face this issue in master, will also re-check in production.

**Comment by amol4anoff** [comment]
works properly in production.
