### ISSUE TITLE
Unit tests 

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/control-center#328]
Unit tests need to be embedded to Tray. 
Branch is `unittest`

**Comment by ibragim13kz** [comment]
10% of unit tests need to be done.

**Comment by ibragim13kz** [comment]
Need to discuss this on Scrum meeting.

**Comment by ibragim13kz** [comment]
@crioto Does CC-team need unit tests? Is this relevant?

**Comment by crioto** [comment]
I don’t think this is possible to cover CC with unit tests. Better to write integration tests for all platforms

**Comment by ibragim13kz** [comment]
@Almansherov Can you create issue about integration tests? Closing this one.
