### ISSUE TITLE
Need more testing for SSDP (Can't see Peers on local network)

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/control-center#399]
1. SubutaiTray is not showing Peers on my local network which are not registered on hub.
2.  SubutaiTray shows only registered Peers, but on some machine it might not show any Peers. (I had this case using machine)

We need more testing on SSDP to clarify my issues and work on improving and debugging SSDPcontroller.

REPRODUCTION:
1. Create Peer. Do not register it on hub. Try to find it in RH list in SubutaiTray (Settings->RH->Resource Hosts)
2. Use Windows. Create Peer. Register it on hub. Try to find it in RH list in SubutaiTray
   
NOTE: Blocks https://github.com/subutai-io/tray/issues/380

**Comment by amol4anoff** [comment]
Reproduced, peers appeared in local peers section.

**Comment by amol4anoff** [comment]
Need to fix it on prod, on master it worked.

**Comment by SEFI2** [comment]
@amol4anoff this feature is not dependent on stage, but it depends on network and the way you created a peer

**Comment by jadilet** [comment]
This issue dependent on https://github.com/subutai-io/agent/issues/633

**Comment by ibragim13kz** [comment]
Works intermittently.

**Comment by jadilet** [comment]
I found reason why CC not finding `LAN Peers` on windows: 
> Windows has the ability to run its own SSDP multicast group. When this service is running, all the received multicast traffic gets "swallowed" by the service. 
>To solve this, go to "Services>SSDP Discovery>Properties>[startup type]=disabled or Manual". After this you will need to stop the service from running by right-clicking on the service "SSDP Discovery" and click "Stop"

**Comment by kurmanbekova6** [comment]
Fixed on Master

**Comment by Almansherov** [comment]
Have tested on ubuntu, windows, debian, and macos machines.

fixed in prod

<img width="378" alt="screen shot 2018-10-31 at 11 46 54 am" src="https://user-images.githubusercontent.com/32430693/47768548-c5065600-dd02-11e8-9854-070a2d456d2e.png">
