### ISSUE TITLE
Make it possible to show password after filling it and mark checkbox "show password"

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/control-center#401]
Now when you fill password, you need to check "show password" before you type it. If you type password and then push "show password" it won't show it. You need to check and then type and it will be shown.
Would be great to implement such feature.

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by amol4anoff** [comment]
Not in production yet.

**Comment by amol4anoff** [comment]
In prod now.
