### ISSUE TITLE
Tray showing available p2p update after fresh install

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/control-center#417]
### Systems
Linux Mint 18.2 Sonya Desktop
macOS Sierra

### Preparations
Uninstalled previous dev tray to install production tray of version 6.3.0. Also I installed the latest production p2p version of 6.2.5.

The tray is still showing that I have a new update to install. If I am in production and there is no version greater than 6.2.5 this should not be the case.

![image](https://user-images.githubusercontent.com/10051386/33509161-6cfbc0ec-d729-11e7-88d0-c33fb7fc2952.png)

I went ahead and selected update. It downloaded something. Have no damn clue what. Would be nice to show me what I am upgrading to. Then I got the failed to upgrade p2p notification. Just for shits and giggles I hit the recheck button. Guess what it showed me I had another update available. 

This needs to get fixed because even if it is minor it drives people crazy thinking they don't have the latest. Plus that failure to upgrade just sucks. You're inviting people. As a user I'm like:

* Shit I need to upgrade damn it or my stuff will not work
* Oh shit the upgrade failed
* I'm stuck in this version without being able to upgrade and my life sucks because of you tray people :-1:

**Comment by akarasulu** [comment]
On macOS I see no error notification of p2p failing after the update. Same process of p2p is still running.

**Comment by SEFI2** [comment]
@akarasulu Tray enables update button when binary of p2p in your machine is different from one that is on kurjun. So, currently p2p binaries in packages and in kurjun were built differently, but has the same version. It will be fixed soon.

**Comment by amol4anoff** [comment]
Fixed in prod.
