### ISSUE TITLE
Create the documentation for users to remove Control Center and p2p

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/control-center#431]
On macOS I would like to clean out my system of Subutai tray and p2p junk from the past. I also want to know officially how to uninstall these things. So there are two parts: 
(1) It seems I have the following packages and I want to clean it up:
```
newton:tray akarasulu$ pkgutil --pkgs | grep subutai
com.subutai-io.SubutaiTray
io.subutai.pkg.mh
io.subutai.pkg.rh
io.subutai.pkg.services
newton:tray akarasulu$ pkgutil --pkgs | grep Subutai
com.subutai-io.SubutaiTray
com.Subutai.Launcher
com.Subutai.P2P
com.Subutai.Tray
```
(2) We need to document how to remove and clean systems of Subutai Tray and P2P across all of the supported platforms going forward. We will document only for 6.x and up. No need to deal with earlier versions.

**Comment by akarasulu** [comment]
Quick 5 minute wiki page please.

**Comment by Erkin97** [comment]
https://github.com/subutai-io/control-center/wiki/How-to-delete-Subutai-Control-Center-and-Subutai-P2P
