### ISSUE TITLE
Terminal on Mac opens in collapsed view when accessing container via tray

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/control-center#452]
If you try to access container on mac via tray, terminal will open, but it will be in collapsed view and you won't be able to detect that it connected properly.

**Comment by akarasulu** [comment]
What is collapsed view can you define it? You mean it is not visible on the desktop but minimized?

**Comment by SEFI2** [comment]
@akarasulu Yes, it is minimized. The user is not notified that the terminal was opened.

**Comment by amol4anoff** [comment]
Seems it is feature of iMac terminal.

**Comment by Erkin97** [comment]
Duplicate of #842
