### ISSUE TITLE
X2Go client doesn't work properly. It fails to launch correctly

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/control-center#502]
Guys please have a look on how x2go works on Mac OS, it can't launch properly, shows error pop up- x2go didn't start correctly and asks to reopen it. Please have a look. I reinstalled it and still it doesn't work in a stable manner.

**Comment by amol4anoff** [comment]
Plus i have some error messages while launching x2go on iMac in production.
<img width="932" alt="x2gofail" src="https://user-images.githubusercontent.com/33647491/34401409-2447e4a6-ebc5-11e7-90c9-f1921d674054.png">

**Comment by amol4anoff** [comment]
And also this - i launch x2go, it is shown on my mac panel, but then it suddenly disappears and nothing happens! Then error message appears:
<img width="866" alt="x2gofail2" src="https://user-images.githubusercontent.com/33647491/34401856-2e7d2e4c-ebc8-11e7-9f82-5fbb61308e73.png">

**Comment by amol4anoff** [comment]
Guys, this is a very critical issue, we have this unstable component on production, let's pay attention for it ASAP.

**Comment by AlinaPenkina** [comment]
On The Windows 10 x2go opens with delay about 3 mins.(production)

**Comment by amol4anoff** [comment]
On iMac it opens on 3rd attempt - Xquartz is not opening properly and it's not possible to access remote desktop from the first attempt. (SSH keys are there).

**Comment by amol4anoff** [comment]
One more trouble - on Linux Mint X2go opens very slowly and also only on the 3-4 attempt. (SSH-keys there).

**Comment by TerGunter** [comment]
Fixed on master

**Comment by ibragim13kz** [comment]
Didn't face this problem in Prod.
