### ISSUE TITLE
MACOS tray keeps crashing 

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/control-center#516]
This happens only on OSX. It leaves no clue in logs. Seems it happens in system level. 
Maybe we should test with debugger for a long time and catch the bug.

**Comment by SEFI2** [comment]
libc++abi.dylib: __cxa_guard_acquire detected deadlock
Abort trap: 6

**Comment by SEFI2** [comment]
We delete c style socket connection, which was making user experience really terrible by slowing the connection time. Plus we got rid of MACOS CRASH

**Comment by amol4anoff** [comment]
It is still crashing on iMac!

**Comment by amol4anoff** [comment]
Didn't reproduce.
