### ISSUE TITLE
Need to optimize the "Connection checker with RH" 

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/control-center#537]
To verify that user can connect to the container via ssh, tray sends a "connect" query using sockets.  If the query was sent successfully, user is able to ssh into the container. Since this function is asynchronous, it can take too long time to verify all containers. Even worse, sometimes it takes too long time to finish the connection for unreachable peers (> 40sec). We should fix it or stop to use connect function until we find the solution.

**Comment by Erkin97** [comment]
* There's no any heavy code running in the connected slots and ssh process also runs in the detached process, so there's no need of optimization

**Comment by ibragim13kz** [comment]
Not relevant.
