### ISSUE TITLE
User can deploy to env. several keys with the same name

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#545]
How reproduce it:
I generate pair keys and deployed public key to env.
After, I deleted this key on local machine, and generate it with the same name, after deployed to env. system allows the same name. (When I do it in hub website, it doesn't allow)
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/59c215b3-7119-4a39-910b-f52f6cdae55f)

**Comment by SEFI2** [comment]
It is not related to tray issue. Hub shold block or notify tray that there already exists such a key.

**Comment by crioto** [comment]
bazaar #5825
