### ISSUE TITLE
SubutaiTray Resource Hungry

### ISSUE THREAD

**Issue by lbthomsen** [subutai-io/control-center#551]
SubutaiTray is eating quite a lot of CPU on my Debian desktop.  This is version 6.5.0 and the below screenshot was made at the lower range - most of the time it is hovering around 20 %.

![image](https://user-images.githubusercontent.com/2730860/35177943-3942c874-fdbf-11e7-9c23-3da75703a0c7.png)

**Comment by SEFI2** [comment]
It seems that it is all because of threads that are stuck. I already found threading issues and fixed. That fix should solve this issue too. I will check it

**Comment by crioto** [comment]
@AlinaPenkina can we reproduce this?

**Comment by ibragim13kz** [comment]
Couldn't reproduce. We'll reopen if needed.
