### ISSUE TITLE
Crash while sshing 

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/control-center#556]
Reproduce, 
1. Open environment(or peer) dialog with active button.
2. Press ssh button
3. Close the dialog immediately 
4. Tray crashes.

**Comment by AlinaPenkina** [comment]
[logs_14.txt](https://github.com/subutai-io/control-center/files/1914564/logs_14.txt)

**Comment by AlinaPenkina** [comment]
I exactly made this steps and CC crashed after it.

**Comment by AlinaPenkina** [comment]
Done
