### ISSUE TITLE
Tray prod on MacOS shows wrong peer owner "my peers" menu

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/control-center#559]
There's peer Anton-1, when i check it in tray, it shows as antonmolchanov020790's, but when i go to -> my peer -> Anton-1 and check owner, it shows another account as owner - amolchanov.

![pokokok.png](https://images.zenhubusercontent.com/5a0a77ce8a75884b90874c56/aa950c8c-b0e0-4c6e-87d5-16677b066e04)

**Comment by SEFI2** [comment]
it shows owner of environment

**Comment by amol4anoff** [comment]
OK, misunderstood

**Comment by akarasulu** [comment]
Notice I cleaned up the issue name and applied the proper tags to enable search mechanisms. Let's adhere to standards @amol4anoff so our lives get easier. No reason to name the product, it's obvious that this is the Control Center right?

**Comment by amol4anoff** [comment]
@akarasulu Ok, great!
