### ISSUE TITLE
[SPIKE] Need to carefully think, research and plan on file transfer to remote desktop using our tray app.

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#561]
We discussed this feature with @SEFI2 today. It would be great if we implement an easy option to transfer files to remote desktop using Tray. User uploads file using Tray, then uses EzDesktop to access that remote host and can easily use those files (videos, test files, music, etc.).

Lets discuss it here and think how can we implement this awesome, cool, fascinating, gorgeous feature!

**Comment by AlinaPenkina** [comment]
@SEFI2 already has some interesting thoughts about it - https://github.com/subutai-io/tray/wiki/File-transfer-system

**Comment by amol4anoff** [comment]
Would be great to implement this feature as soon as possible.

**Comment by samsonbek** [comment]
It must be possible for both upload and download. I mean,  user may also want to download files from remote desktop or server.

**Comment by amol4anoff** [comment]
@samsonbek exactly!

**Comment by akarasulu** [comment]
I have no idea if these guys are just thinking upload. Big mistake if they are. Someone please make sure they understand that upload only is absolutely a waste. @Shahrizada @SEFI2 What's matrix guy's handle?
