### ISSUE TITLE
UI of file transfer system 

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/control-center#564]
Here I will post sample UI for file transfer system. Please feel free to comment below. 
First:
![image](https://user-images.githubusercontent.com/22672448/35766355-0a4ec296-0901-11e8-8bfc-8a5a97e31ba3.png)

**Comment by amol4anoff** [comment]
OK.

**Comment by Erkin97** [comment]
Changed UI:
![image](https://user-images.githubusercontent.com/22586805/35908355-9c4840fc-0c1a-11e8-8628-6d330d5c1e71.png)

**Comment by SEFI2** [comment]
Changed Environments dialog:
![image](https://user-images.githubusercontent.com/22672448/36014918-59abbeae-0d96-11e8-8580-18099b6fd1e2.png)

Issue for this change:
https://github.com/subutai-io/tray/issues/605

**Comment by SEFI2** [comment]
![image](https://user-images.githubusercontent.com/22672448/36135151-8bca43c2-10b3-11e8-8e1a-de246f5c776e.png)

**Comment by samsonbek** [comment]
what if user wants to upload same set of file into several container of environment? Maybe on this form https://github.com/subutai-io/tray/issues/564#issuecomment-363707002  we add list of containers for given environment, so user can select (checkboxes or rows) containers and then upload selected files into them.

**Comment by akarasulu** [comment]
> Use case: user has cluster with same service running in several containers .

We want to upload to all of them. Makes sense.

My take: 

1. The feature is not common (other apps that transfer stuff do not usually have it) 
2. Can't copy their intuitive UX example, we need to think of the feature carefully. 
3. First let's get it working right for one destination target. 
4. User might configure a `destination group` for this either right when transferring etc with some intelligence: i.e. if I see user transferring to one container and we see there are 3 containers of the same time we can ask if they want to do this for all 3 of them.

Please make the multi-destination transfer option a separate issue so we can close this one when done and move on to that one separately.

**Comment by SEFI2** [comment]
![image](https://user-images.githubusercontent.com/22672448/36190249-62ff70f6-1181-11e8-9519-1c9eefd9cba7.png)

**Comment by SEFI2** [comment]
Changed UI. Enabled Dragging from users local repository. Added threads (not finished)

![image](https://user-images.githubusercontent.com/22672448/36251720-62080320-126c-11e8-9e95-dd09bd338dc9.png)
