### ISSUE TITLE
p2p status modification

### ISSUE THREAD

**Issue by Erkin97** [subutai-io/control-center#582]
when user press P2P status button, must do following steps:
1) launch p2p.service if state "not launched"
2) open installation link of p2p if state "failed"
3) tell that everything is ok if state "running"
4) tell to wait if state "loading"

**Comment by crioto** [comment]
> open installation link of p2p if state "failed"
I don't agree with this.
You need to extend this functionality and check if p2p exists. If it's not only THEN you should send user to a website.
If it's installed, but can't start we need to do something else. Show notification - that p2p can't start. 
Also, note, that p2p can take some time to start, so after you try to launch it you should wait for up to 60 seconds before considering it as failed.

**Comment by amol4anoff** [comment]
Done.

**Comment by amol4anoff** [comment]
@Erkin97 Recommendation regarding P2P status button:

1. When P2P is installed and works - "P2P is running", when user mouse over it, show tooltip - "P2P is now ready"
2. When P2P is installed but is not running - "P2P is loading/not running - when mouse over, tooltip - "P2P is not running, please start it"
3. When P2P is absent - "P2P is not installed" - tooltip - please install p2p daemon, "suggest user a link to p2p installation on subutai.io"

**Comment by amol4anoff** [comment]
Done.

**Comment by amol4anoff** [comment]
Works properly.
