### ISSUE TITLE
Need to build libssl1.0 statically and add to tray

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/control-center#591]

**Comment by crioto** [comment]
What help do you need? Experiencing any problems with this task?

**Comment by SEFI2** [comment]
@crioto I haven't yet got the proper way to do it. Builder already gets the `.so` libraries and puts it inside the tray. And I just wanted to do same and added script which gets the `libssl.so.1.0.0` from builder machine and puts inside the package(last lines: https://github.com/subutai-io/tray/blob/dev/deb-packages/deb-packages-internal/dependencies.sh ). But I am not really sure if it will work in this way.  Testing it right now and haven't got any positive results yet.

**Comment by crioto** [comment]
You should know, that `.so` is a dynamic library. and this `libssl.so.1.0.0` is just a symbolic link to `libssl.so` (or vice versa). Statis library is `.a` file, which is basically an archieve (`ar`) of `.o` object files produced by compiler.

**Comment by amol4anoff** [comment]
@erkin how to check that this library is installed?

**Comment by Erkin97** [comment]
@amol4anoff try to install CC on fresh Debian

**Comment by amol4anoff** [comment]
Done.

**Comment by amol4anoff** [comment]
Fixed.
