### ISSUE TITLE
Need to refactor RestWorker.cpp 

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/control-center#593]
`QJsonDocument doc = qjson_doc_from_arr(reply_arr, err_code);`
  `QJsonArray doc_arr = doc.array();`

  `std::vector<CMyPeerInfo> lst_res;`
  `for (auto i : doc_arr) {
    if (i.isNull() || !i.isObject()) continue;
    lst_res.push_back(CMyPeerInfo(i.toObject()));
  }`
It is expected in further parts that NON_JSON or EMPTY json files could be retrieved from rest. So we need to have many `checkers` in REST controller files, which will check for potential errors to prevent crashes.

**Comment by ibragim13kz** [comment]
Minor changes in ```CRestWorker::qjson_doc_from_arr```, actually cannot be tested.
