### ISSUE TITLE
Use checkbox instead of Buttons 

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/control-center#605]
For each container, tray provides two buttons (SSH & DESKTOP). Suppose, the user has 10 containers. So he will have 20 buttons on one dialog, and most of the `DESKTOP` button would be disabled. Soon the third button will be added, which is `Upload` button. But instead of adding button all over the dialog, we can use checkboxes to select containers and  `EZ-SSH, EZ-DESKTOP or EZ-UPLOAD` into them. Design of dialog would be improved also.

**Comment by AlinaPenkina** [comment]
Done.
