### ISSUE TITLE
[SPIKE] Peers Control System

### ISSUE THREAD

**Issue by Erkin97** [subutai-io/control-center#612]
* Allow users to control their peers
* Create peer (done)
* Halt / Up / Destroy peer (done)
* Register/UNregister peer (done)
* Check if vagrant, plugins, vm is installed (done)
* Install them if not installed (done)
* Rework UI for peer management (done)
* Reload peers (done)
* Change configuration of peer (done)
## TODO
* TEST
* Bug fixing, optimization
* New fancy icons for buttons
* Informative logs
* Error handling

**Comment by akarasulu** [comment]
Some ideas and notes from our discussion:

- First start with local peer ops to perhaps leverage global-status (YMMV sometimes cache gets dirty but can be cleaned) which might save you from having to track where the vagrant peers are in the tray.
- Next you might want to use SSH for managing remote peers on the LAN

Don't just think about managing peers. There are resource hosts that can be added to grow a peer. Think about that part while doing your design so you don't have to warp it out of shape to enable RH and Peer management. 

Think of things like what's the common denominator things you can do to any vagrant VM. One layer above that are functions for resource hosts. Than the next layer peers. Think about how you can register many resource hosts with a single peer. If you do this right it can really enable users. But it need to be easy to understand automatically (intuitive).

My two cents...

**Comment by akarasulu** [comment]
Another thing we should do is make it so the tray can install all that is needed to get going with peers and resource hosts. This way it becomes a kind of peer and RH launcher/manager. There are a few parts to this:

Detecting and Installing a Hypervisor
-------------------------------------

A a hypervisor on the system is needed to run a VM. Currently our boxes only support VirtualBox but shortly we will support libvirt for Linux. It would be nice for the tray to at least offer to install VIrtualBox if no hypervisor is installed on the system. It should be able to pull the software directly from the website or from our CDN to offer speedups when cache nodes are used locally.

I would like to support a few providers down the line so it would be nice to use a nice design pattern to be able to add these on an as needed basis. Some we will be able to install for the user and some we may not.

Detecting and Installing a Vagrant
----------------------------------

We need obviously need to install vagrant. However what might not seem obvious is the need to install plugins. We already have two plugin dependencies:

- vagrant-vbguest
- vagrant-subutai

If we use a hypervisor other than VirtualBox we will need to install the provider for it which is yet another plugin for vagrant. By default Vagrant is already equiped to support VirtualBox so there's no need to worry installing a provider plugin for it.

> Again options should exist for pulling vagrant down directly from Hashicorp or our CDN to take advantage of the local cache.

**Comment by Erkin97** [comment]
## What is done so far
Create peer
----------------------------------
![create_peer 2](https://user-images.githubusercontent.com/22586805/37240425-3b629b20-2475-11e8-80fe-4fd6599f2988.png) 
* When, user press create button, CC creates directory for peer with configuration files and calls "vagrant up" in popup terminal.

Updated my peer menu
----------------------------------
* Added local machine peers
* Each peer has four state:
1) Turned off
2) Running
3) Registered to Bazaar
4) Not in your machine

Updated peer dialog box
----------------------------------
* New section "Advanced settings"  to control peer using vagrant (only for local machine peers)
![peer_box](https://user-images.githubusercontent.com/22586805/37240522-be562690-2476-11e8-97f7-3e4705244bb1.png)
* **Start / Stop** Implemented
* **Register / Unregister** Implemented
![peer_box4](https://user-images.githubusercontent.com/22586805/37240523-d054d80a-2476-11e8-9793-10a96564ef2e.png)

**Comment by AlinaPenkina** [comment]
Done.
