### ISSUE TITLE
Register/Unregister button for the peers

### ISSUE THREAD

**Issue by Erkin97** [subutai-io/control-center#615]
Allow users to register and unregister to the hub their peers

**Comment by Erkin97** [comment]
* implemented buttons register/unregister peer
* implemented dialog box for register/unregister peer
* left to do error handling
* left to refactor code
![register](https://user-images.githubusercontent.com/22586805/36248247-0434277a-1261-11e8-92d3-971e89915fc1.png)

**Comment by TerGunter** [comment]
fixed on prod
