### ISSUE TITLE
Transfer file system background action blocker

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/control-center#622]
When host is unknown and you first ssh into container, you get the following question from terminal:
![image](https://user-images.githubusercontent.com/22672448/36247929-f1b77846-125f-11e8-9ef4-42c667cf66be.png)

But when you `scp` in the background, it is not easy to skip this step.
One of the solutions would be to warn users first to `ssh` into container and then to use `File Transfer System`.

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
