### ISSUE TITLE
Make create folder button for File Transfer System 

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/control-center#625]

**Comment by SEFI2** [comment]
Also cool to make remove button

**Comment by Almansherov** [comment]
Have not seen any `create folder` button:

![image](https://user-images.githubusercontent.com/32430693/46463365-97b49f80-c778-11e8-90a6-9ea9786f6936.png)

would be cool if you guys put more information

**Comment by Almansherov** [comment]
Implemented on master:

![image](https://user-images.githubusercontent.com/32430693/46469860-87f18700-c789-11e8-8b25-a5194b102b04.png)

I also checked the functionality.
So, `New Folder` was created succesfully.

**Comment by Almansherov** [comment]
Fixed in prod:

![image](https://user-images.githubusercontent.com/32430693/47715250-32d05600-dc0d-11e8-9e88-f69188b191b5.png)
