### ISSUE TITLE
Notification history issue

### ISSUE THREAD

**Issue by Erkin97** [subutai-io/control-center#626]
* Message tab is too wide and gives effect of all notifications cleared when you double tap on notification message which should not happen

![screenshot from 2018-02-15 17-23-58](https://user-images.githubusercontent.com/22586805/36254379-192f353e-1275-11e8-84bc-ff150e711acf.png)

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
