### ISSUE TITLE
File Transfer Progress Bar

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/control-center#632]
For each file transferred, we need to have a progress bar, which shows the state of the file being transferred.

**Comment by Almansherov** [comment]
Not relevant anymore

**Comment by akarasulu** [comment]
What does this mean?

**Comment by Almansherov** [comment]
This issue is not going to be fixed in current cc. Even if it is important enough to have, it should be included in the functionality of subutron. 
Do you think I need to keep it open?
