### ISSUE TITLE
Some files are failing to be uploaded or downloaded

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/control-center#633]
Need to find the bug of this failure or give the exact feedbacks to users.

**Comment by Erkin97** [comment]
* Now you can download remote files to any directory in /home/usr/*, otherwise it fails

**Comment by amol4anoff** [comment]
I can now upload/download files of different types - text, video, photo. And sizes of 100+ mb. We need to deploy to prod, as there's problem with upload there.
