### ISSUE TITLE
Delete empty message window.

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#676]
When user pushes button "SSH" but he doesn't have ssh key, opens empty window.
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/7dc108e1-fabf-46ba-8360-1f3ba86c05a8)
When ssh key is existing then this window shows path to ssh key on local PC.

**Comment by amol4anoff** [comment]
Done.
