### ISSUE TITLE
When no key deployed to containers CC doesn't report any errors

### ISSUE THREAD

**Issue by crioto** [subutai-io/control-center#680]
I was testing on dev cc
`Linux laptop.crioto.com 4.15.6-1-ARCH #1 SMP PREEMPT Sun Feb 25 12:53:23 UTC 2018 x86_64 GNU/Linux`
After clicking on SSH button my terminal (`terminator 1.91`) went to local computer and didn't show any errors. After I've added key to environments it started to SSH normally.

**Comment by amol4anoff** [comment]
Done.
