### ISSUE TITLE
SSH-keys can be removed by control center without any actions.

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#707]
1. I deployed ssh key to env.  and after sometime a needed to deploy other key to other env. In fact ssh key was deployed to new env. and deleted from old one.
2. I deployed key to env. it was working ( I was able to connect with container by SSH connection)  after some time SSH-key disappeared from env.
[logs_09.txt](https://github.com/subutai-io/control-center/files/1796791/logs_09.txt)
[logs_10.txt](https://github.com/subutai-io/control-center/files/1796792/logs_10.txt)
[logs_12.txt](https://github.com/subutai-io/control-center/files/1796793/logs_12.txt)
[logs_13.txt](https://github.com/subutai-io/control-center/files/1796794/logs_13.txt)
[logs_14.txt](https://github.com/subutai-io/control-center/files/1796795/logs_14.txt)
[logs_15.txt](https://github.com/subutai-io/control-center/files/1796797/logs_15.txt)
[logs_16.txt](https://github.com/subutai-io/control-center/files/1796798/logs_16.txt)
[logs_17.txt](https://github.com/subutai-io/control-center/files/1796799/logs_17.txt)

**Comment by Erkin97** [comment]
*  how to reproduce, add key with same name from different machines

**Comment by AlinaPenkina** [comment]
One more moment:
I have deployed ssh keys on one machine, after I need to deploy other keys from other machine(keys names aren't the same)
Result: When I deployed other keys from other machine, CC deleted my previous keys from envs.

**Comment by AlinaPenkina** [comment]
This is very important.

**Comment by Erkin97** [comment]
* When you remove mark from environment it's ssh key will be deleted, this is a feature in control center

**Comment by Erkin97** [comment]
* To avoid this kind of misunderstandings need to make more user friendly #1023

**Comment by AlinaPenkina** [comment]
We need to improve this form #1023 So this issue can be closed.
