### ISSUE TITLE
Install software [EPIC]

### ISSUE THREAD

**Issue by Erkin97** [subutai-io/control-center#708]
Allow users to install from cc:
* p2p
* x2go
* vagrant
* Oracle VM virtualbox

**Comment by Erkin97** [comment]
* p2p is done

**Comment by akarasulu** [comment]
I guess this is just partially done right? BTW usually we use an epic with sub-issues for big jobs like this. FYI.

**Comment by Erkin97** [comment]
* X2GoClient is done:
  * Users can install X2GoClient from "About" menu
* Vagrant is done:
  * Users can install Vagrant and its plugins from "About" menu

**Comment by AlinaPenkina** [comment]
Fixed.

**Comment by amol4anoff** [comment]
Done (prod).
