### ISSUE TITLE
Review/rework notifications

### ISSUE THREAD

**Issue by crioto** [subutai-io/control-center#711]
![screen shot 2018-03-11 at 10 22 53 pm](https://user-images.githubusercontent.com/671147/37255738-d69c9d6a-257a-11e8-83ef-23cecac5c2e9.png)
This happened during bazaar deployment. This is very rare situation when CC needs to notify user about Bazaar page being not found (basically this should never happen!). Instead we can know that if service returns 404 for any of the REST endpoints - it means something is happening on bazaar side and we can enter idle mode, unless we start getting acceptable HTTP responses.

**Comment by amol4anoff** [comment]
Done.
