### ISSUE TITLE
Need to add option to delete files, that user uploaded to remote desktop using file transfer

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/control-center#716]
Now it is not possible to remove files that are uploaded to storage via file transfer in CC. Would be great to implement it ASAP.

**Comment by ibragim13kz** [comment]
@amangeldizhusubaliev Need to add refresh after each action, because it doesn't update by itself. So right now we have to click 'Refresh' button every time after each performance.

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by Almansherov** [comment]
Tested on Debian, Windows, MacOS, and Ubuntu.
Created environment
added ssh key
copied a file using file transfer:

<img width="896" alt="screen shot 2018-10-31 at 11 31 07 am" src="https://user-images.githubusercontent.com/32430693/47768070-95eee500-dd00-11e8-809c-84f3e3ccaa54.png">

Fixed in prod
