### ISSUE TITLE
x2go installation from CC

### ISSUE THREAD

**Issue by Erkin97** [subutai-io/control-center#724]
#708

**Comment by amol4anoff** [comment]
Done.

**Comment by Almansherov** [comment]
Successfully repeated the installation couple of times:

![image](https://user-images.githubusercontent.com/32430693/49505111-abe05000-f840-11e8-98c7-affc79576e87.png)

Fixed in master

**Comment by Almansherov** [comment]
Repeated the steps in prod.
Fixed
