### ISSUE TITLE
Install browser and E2E plugin

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/control-center#734]
Goal
----

One of the most important components for clients is the E2E plugin for browsers. We presently support this plugin on the following browsers:

* Chrome (preferred browser on all operating systems)
* FireFox (on all operating systems)
* Edge on Windows
* Safari on Mac OS

The browser plugin's installation **MUST** be supported by the Control Center. It's installation gets to be a bit tricky because of all the options available. This issue defines one way this can be handled with the proper user interaction.

Interaction Requirements
-------------------------

In general CC always opts for lazy installation. Items are not installed until the user performs some action requiring the missing software to be present on the system. Furthermore, CC should always prompt that it is installing software and explain why it is needed. It should also provide feedback during the installation process after getting approval to install and starting the operation with clear completion results.

> CC **MUST** always verify signatures, and checksums on installed software from the CDN

### Prerequisites

* CC should check to see which browsers and their versions are installed on the system using various platform specific mechanisms.
* CC should check each browser to see if the plugin is installed in the browser and what version the plugin is.

### Installation Triggers

When launching browser windows or tabs to get to peers or the bazaar CC should check if it has already installed the necessary software for the browser it is using for the launch operation. It should also check that the proper most recent version of the plugin is being used otherwise prompt to upgrade it.

### Browser Choices

If the user has yet to install the browser plugin on any one of the browsers on the system CC will prompt the user. The user can chose to install the preferred Chrome browser if it is not installed or to select the native browser. Based on the platform options change:

* Windows: Chrome, Firefox, Edge
* Mac OS: Chrome, Firefox, Safari
* Linux: Chrome, Firefox

CC should note the decisions made by the user in the past in it's persistent configuration files. So if Chrome is not installed on Windows, and the user just selects Edge because it is there already, then we do *NOT* ask the user again. Change browser settings should be available in the settings section to allow the user to unset or reset these values.

Once the browser is selected, then we:

1. Install the browser if not present or it needs an update to an earlier version
2. Install the E2E plugin in the selected browser already present on the system

Upgrades
----------

Every launch should probably check for available updates if a check was not already done that day. So the last check date should be used. The About page should show the version of the browser, whether or not it needs an update and the version of the E2E plugin and whether or not it needs an update. Right now we've only got the version of the chrome browser used being shown and no update options exist for it.

**Comment by Erkin97** [comment]
## First steps
* Allow to choose default browser
* CC will use only this browser and check plugin only on that browser
<img width="690" alt="screen shot 2018-04-24 at 12 25 49 pm" src="https://user-images.githubusercontent.com/22586805/39169738-c60dd344-47ba-11e8-910e-96427927f1a6.png">

**Comment by ibragim13kz** [comment]
Done in Master.

**Comment by Almansherov** [comment]
Successfully installed e2e plugin to firefox browser

![image](https://user-images.githubusercontent.com/32430693/47696689-e6b5ef00-dbd5-11e8-87c6-26a0368aab32.png)
