### ISSUE TITLE
Make  sure users can do actions with  p2p via Controle Center .

### ISSUE THREAD

**Issue by Shahrizada** [subutai-io/control-center#766]
When user clicks on p2p button some actions should appear:
start. stop, restart
something like this

**Comment by amol4anoff** [comment]
Done.

**Comment by amol4anoff** [comment]
Done in prod.

**Comment by AlinaPenkina** [comment]
On MAC OS nothing happens when user pushes p2p button.

**Comment by AlinaPenkina** [comment]
Fixed on master.

**Comment by AlinaPenkina** [comment]
It works intermittently on MAC OS. Please have a look. @Erkin97

**Comment by Erkin97** [comment]
It was fixed in prod , after I reworked notifcations

**Comment by ibragim13kz** [comment]
Failed in Prod on Debian 9.

**Comment by Erkin97** [comment]
* For Linux machines I reworked restart scripts

**Comment by amangeldizhusubaliev** [comment]
Fixed on master.

**Comment by amangeldizhusubaliev** [comment]
fixed on prod.
