### ISSUE TITLE
No minimize, close, maximize buttons in Debian sctretch

### ISSUE THREAD

**Issue by Erkin97** [subutai-io/control-center#770]
![screenshot from 2018-03-28 16-09-36](https://user-images.githubusercontent.com/22586805/38022959-d4490eb0-32a2-11e8-8870-3bea085dccbb.png)
* OS: Debian GNU/Linux 9.4

**Comment by Erkin97** [comment]
![screenshot from 2018-03-28 16-36-07](https://user-images.githubusercontent.com/22586805/38024281-5a126ac0-32a6-11e8-9e4b-5538908f2c60.png)
* Fixed
* Added button manually

**Comment by amol4anoff** [comment]
Fixed:

<img width="912" alt="db45" src="https://user-images.githubusercontent.com/33647491/38555106-c52a666a-3ce6-11e8-84d2-227ed55df1b5.png">

**Comment by amol4anoff** [comment]
Done in prod.
