### ISSUE TITLE
SSH key deployment takes too much time, even when environment is healthy and p2p state is ready

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/control-center#775]
I face error in MacOS - create ssh-key, deploy it to environments, they shift to under modification state, then they become healthy and p2p state is ready, after this i press ssh button, but have error message "no keys deployed". Logically keys should be there once environment is healthy and p2p state is ready.

**Comment by TerGunter** [comment]
fixed on master

**Comment by TerGunter** [comment]
fixed on prod
