### ISSUE TITLE
p2p is running, but in tray it looks like isn't installed.

### ISSUE THREAD

**Issue by EsKaRioT** [subutai-io/control-center#779]
it appeared after the update p2p on my machine
OS Win10
![good](https://user-images.githubusercontent.com/29449371/38128037-a6d9acd6-341a-11e8-9233-125bde47b97a.png)
[logs_12.txt](https://github.com/subutai-io/control-center/files/1862892/logs_12.txt)
[logs_13.txt](https://github.com/subutai-io/control-center/files/1862893/logs_13.txt)

**Comment by AlinaPenkina** [comment]
In CC it shows also p2p isn't running.
