### ISSUE TITLE
Failed to refresh remote directory at OS( mac,debian, win ) in СС at all peers PROD

### ISSUE THREAD

**Issue by EsKaRioT** [subutai-io/control-center#781]
![image.png](https://images.zenhubusercontent.com/5ab32bec4b5806bc2bcbe2e1/475e1878-b733-474d-91d9-e0683a021d3c)

**Comment by ibragim13kz** [comment]
This error depends on p2p connection. If the connection is OK, then refresh also works.

**Comment by amol4anoff** [comment]
Still having this problem on macos (master). SSHed to container, but unable to refresh remote directory:

<img width="1802" alt="refresh1" src="https://user-images.githubusercontent.com/33647491/38545977-31a1c5fa-3ccd-11e8-98ba-d822488e9792.png">

**Comment by AlinaPenkina** [comment]
Fixed on master.
