### ISSUE TITLE
Change CC logo in navbars

### ISSUE THREAD

**Issue by zubaidullo** [subutai-io/control-center#782]
Change CC icon in navbars, CC logo is very dark and on dark desktop theme it's almost invisible. It's better to outline with lighter color (will 2 colors dark and light) if desktop theme is light dark side will be visible, otherwise, light side 

From below pic. we can see only CC icon invisible. 
![image](https://user-images.githubusercontent.com/4469949/38163015-a355fb24-350e-11e8-8f97-26d20c21e325.png)

**Comment by TerGunter** [comment]
fixed

**Comment by amangeldizhusubaliev** [comment]
done
