### ISSUE TITLE
During ssh keys deploying, CC changes ssh-keys storage path.

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#788]
[logs_15.txt](https://github.com/subutai-io/control-center/files/1871108/logs_15.txt)
How to reproduce:
1. Create environment.
2. After it became healthy, deploy ssh key to this env.
3. Create another env.
4. After it became healthy mark only this environment for deploying key, and deploy.
Result: In CC settings, ssh-key storage shows wrong path, that is why user can not to get by ssh into this container.

**Comment by ibragim13kz** [comment]
Still face this bug.

**Comment by TerGunter** [comment]
fixed on master

**Comment by amangeldizhusubaliev** [comment]
done
