### ISSUE TITLE
CC crashes when user pushes ssh key management button

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/control-center#791]
Case - run CC, push ssh key management button (ssh keys should not be deployed before that). Result - CC quits abruptly. OS - MacOS, Windows. MASTER.

**Comment by amol4anoff** [comment]
[logs_directory_2018.04.05-master.zip](https://github.com/subutai-io/control-center/files/1878789/logs_directory_2018.04.05-master.zip)

**Comment by amol4anoff** [comment]
Another similar case - open CC, open environment dialogues, wait for some time - 5-10 minutes. Then click ssh button - result: cc quits immediately once button is pressed. (MacOS, Master)
@Erkin97

**Comment by amol4anoff** [comment]
Tried several times, error was not reproduced.

**Comment by amol4anoff** [comment]
Correction: crashed on windows.

**Comment by AlinaPenkina** [comment]
done.
