### ISSUE TITLE
Make update variables global

### ISSUE THREAD

**Issue by Erkin97** [subutai-io/control-center#804]
Implementation of this will solve two bugs:
1) when installation of components from About fails, you can't press again Update/Install buttons
2) close About Dlg while installing component, you can't press again update/install buttons

**Comment by ibragim13kz** [comment]
1. Can't reproduce component's failure during installation. 
2. Reproduced. So, wanna notice that after closing "About" window, component (x2go) was installed anyway.

**Comment by amangeldizhusubaliev** [comment]
done

**Comment by TerGunter** [comment]
Fixed on master

**Comment by amangeldizhusubaliev** [comment]
done
