### ISSUE TITLE
SSH-key manager

### ISSUE THREAD

**Issue by Erkin97** [subutai-io/control-center#813]
* Crash when rest api to bazaar
``` [15:52:16] [..\hub\src\RestWorker.cpp(806)] Critical: Send request network error : Error transferring https://masterbazaar.subutai.io/rest/v1/tray/environments/check-key - server replied: Server Error (in function class QByteArray __cdecl CRestWorker::send_request(class QNetworkAccessManager *,class QNetworkRequest &,int,int &,int &,int &,class QByteArray,bool))```

**Comment by Erkin97** [comment]
```

**Comment by Erkin97** [comment]
[solution](https://forum.qt.io/post/374287)

**Comment by TerGunter** [comment]
Fixed on master

**Comment by amangeldizhusubaliev** [comment]
fixed on master.

**Comment by amangeldizhusubaliev** [comment]
fixed on prod.
