### ISSUE TITLE
[Improvement of User Interface] Couldn't Get Where The Destroy Button Is

### ISSUE THREAD

**Issue by azretkenzhaliev** [subutai-io/control-center#833]
(see upper-right corner)
Maybe it is better to show "Destroy" button right there, without need to press "Advanced Settings", because anyway user will need this button and that's not something that needs to be hidden under "Advanced Settings"?

![screenshot from 2018-04-12 11-45-41](https://user-images.githubusercontent.com/7948741/38659080-9368c310-3e49-11e8-806b-096141e3b460.png)

**Comment by Erkin97** [comment]
* Press advanced settings button

**Comment by Erkin97** [comment]
* show advanced commands if peer in your machine

**Comment by AlinaPenkina** [comment]
Fixed on master.

**Comment by TerGunter** [comment]
fixed on prod
