### ISSUE TITLE
In peer creation page error message that user can't use symbols in peers name. On master Linux, Windows

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#846]
User can't create peer, because of error that he can't use symbols, but in peer name aren't exists any symbols except letters.  
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/749bb3a6-8b63-4e46-b311-5a9a2f46607b)

**Comment by TerGunter** [comment]
fixed on master

**Comment by TerGunter** [comment]
fixed on prod
