### ISSUE TITLE
Component installation does not fail when loses connection (WindowsOS) 

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#862]
There is no any notification telling "no connection" or "no internet" for a user when the network breaks down.

**Comment by ibragim13kz** [comment]
Installation still does not fail when connection is lost.

**Comment by Almansherov** [comment]
Deleted The Subutai Boxes
Started installation process
and in the middle of I disabled the ethernet connection.
CC gave me a message that connection is lost.
Fixed in prod
