### ISSUE TITLE
If p2p instance failed to start due to TUN/TAP problems DHT connection is still active

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#863]
If p2p instance failed to start due to TUN/TAP problems DHT connection is still active

**Comment by Erkin97** [comment]
* p2p related issue

**Comment by AlinaPenkina** [comment]
Issue moved to [subutai-io/p2p #881](https://github.com/subutai-io/p2p/issues/881) via [**ZenHub**](https://www.zenhub.com/)
