### ISSUE TITLE
CC can not indicate components that was installed not via CC

### ISSUE THREAD

**Issue by TerGunter** [subutai-io/control-center#867]
CC can not indicate p2p that was installed from the website and offers to install it again from About menu. 
![screenshot_1](https://user-images.githubusercontent.com/33474101/39081379-2da4ba14-4562-11e8-897f-8470c5de6d32.png)

**Comment by amangeldizhusubaliev** [comment]
same issue with virtualbox, CC suggests to install it, but I've already have virtualbox.
![scrvb](https://user-images.githubusercontent.com/38368928/39081422-df74d828-4562-11e8-986a-ddba7b42092e.png)

**Comment by TerGunter** [comment]
[logs_12.txt](https://github.com/subutai-io/control-center/files/1934231/logs_12.txt)

**Comment by Erkin97** [comment]
* CC might show you old information, so you need to press "RECHECK" after you installed components

**Comment by TerGunter** [comment]
@Erkin97 I used the button "recheck" many times, and only after that I create issue

**Comment by TerGunter** [comment]
i still face this problem it doesn't recognize p2p that i did download from website
![screen shot 2018-04-23 at 4 48 02 pm](https://user-images.githubusercontent.com/38347277/39122323-61b8beda-4716-11e8-83e9-10fcfe6fc41b.png)

**Comment by AlinaPenkina** [comment]
Fixed on master.
