### ISSUE TITLE
CC stuck and all windows became stuck for some moment

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#870]
All OS getting stuck because of CC.
OS-Windows 10.

**Comment by AlinaPenkina** [comment]
[logs.txt](https://github.com/subutai-io/control-center/files/1934313/logs.txt)

**Comment by Erkin97** [comment]
* fixed wrong deletion of fingerprint should fix this problem

**Comment by ibragim13kz** [comment]
Need to test more on Win10.

**Comment by AlinaPenkina** [comment]
Now, I don't face this problem.
