### ISSUE TITLE
Control Center crashed on Windows.

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#873]

**Comment by AlinaPenkina** [comment]
[logs.txt](https://github.com/subutai-io/control-center/files/1934409/logs.txt)

**Comment by Erkin97** [comment]
* fixed wrong delations of fingerprints which caused this crash

**Comment by ibragim13kz** [comment]
Didn't face this error on Win10 for a long time.

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by kurmanbekova6** [comment]
While we don't face this problem
