### ISSUE TITLE
Can't uninstall Oracle VirtualBox from Mac OS, Ubuntu and Debian with normal way

### ISSUE THREAD

**Issue by TerGunter** [subutai-io/control-center#883]
Uninstallation is impossible with usual way, but possible via CLI on Mac OS and only with special scripts on Ubuntu and Debian.
Steps to reproduce on Mac:
1. Open applications, find VirtualBox
2. Move to stash
3. Open on CC "About" menu => Virtual box is not uninstalled

**Comment by Erkin97** [comment]
* I will create WiKi

**Comment by TerGunter** [comment]
Done
