### ISSUE TITLE
Install linux headers for virtualbox

### ISSUE THREAD

**Issue by Erkin97** [subutai-io/control-center#890]
On fresh linux machine linux headers might not be installed which causes to fail virtualbox

## Expected Behavior
Install missing linux headers on Linux machines

## Current Behavior
Ignores

## Possible Solution
add additional scripts to virtualbox installer

## Steps to Reproduce
1. Install fresh Linux machine
2. Install virtualbox from CC
3. Fails to run peer
4.

**Comment by amangeldizhusubaliev** [comment]
successfully installed on fresh debian 9. 
Fixed on prod.
