### ISSUE TITLE
Add icon to launcher bar on linux base systems

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#905]
Add icon to launcher bar on linux base systems
![Screenshot from 2018-04-26 11-12-31.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/3aa82cd4-79af-4e09-b707-323e1449f6a5)
* HOW TO  REPRODUCE : run ```
SubutaiControlCenter``` from terminal

**Comment by TerGunter** [comment]
Fixed on master

**Comment by ibragim13kz** [comment]
Fixed in Prod.
