### ISSUE TITLE
check if cmd is launchable on WinOS

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#906]
When CC fails to run terminal on Windows and freezes main program

## Expected Behavior
Tell that cmd is not launchable

## Current Behavior
CC just freezes

## Possible Solution
put checker before running command on terminal

## Steps to Reproduce
1. Make cmd not working
2. Run ssh to container
3.
4.

**Comment by ibragim13kz** [comment]
Not relevant. Closing.
