### ISSUE TITLE
Replace gksu

### ISSUE THREAD

**Issue by Erkin97** [subutai-io/control-center#908]
* gksu was removed on new Ubuntu and Debian (Debian 10 (not released) and Ubuntu 18.04) from their repositories.

**Comment by Erkin97** [comment]
* Replacement gksu from control center for all linux based machines is a painful procedure, which may cause more issues and bugs. I'm thinking on making a separate package for Ubuntu 18.04 users

**Comment by happyaron** [comment]
gksu is incompatible to wayland so it was abandoned, will have a look into this as well.

**Comment by Erkin97** [comment]
I removed gksu, and used PolKit

**Comment by Erkin97** [comment]
* We used gksu for installing CC components, we need to test installing components with PolKit

**Comment by amangeldizhusubaliev** [comment]
CC components installed without problems on Ubuntu 18.04.

**Comment by amangeldizhusubaliev** [comment]
fixed on prod.

**Comment by liquuid** [comment]
Hi, an user had problems on ubuntu 18.04. Check it out https://subutai-io.slack.com/archives/C107FJU94/p1527807887000394
