### ISSUE TITLE
Increasing functionality of File Transfer

### ISSUE THREAD

**Issue by Erkin97** [subutai-io/control-center#910]
* Sorting by size, alphabetically, date, type
* Better ui (resizing width and etc)
* Create folder
* Delete files or folders
* Show progress of transferring (complex)

**Comment by samsonbek** [comment]
- change columns width in directory files list. If file name is long, there is a need to increase width of column to see full name. Also selected file full name might be showed in some status bar, for user convenience.

**Comment by AlinaPenkina** [comment]
We need to add automatic refresh after file uploading, because now if file already uploaded to server, it doesn't appear in list, user needs to refresh the window.

**Comment by Almansherov** [comment]
Completed
