### ISSUE TITLE
Provide a documentation on how to setup a development environment

### ISSUE THREAD

**Issue by crioto** [subutai-io/control-center#912]
We need to develop a guide on how to setup a development environment for each operating system

**Comment by akarasulu** [comment]
It would be nice if in addition to this we had a vagrant box targeting each OS. Even for Mac we can have a parallels, or fusion VM to do so if the developer is on a Mac to begin with. This can reduce the barrier to near zero for people to get started.

**Comment by amangeldizhusubaliev** [comment]
https://github.com/subutai-io/control-center/issues/1115

**Comment by ibragim13kz** [comment]
Done.
