### ISSUE TITLE
Cover main menu with tooltips

### ISSUE THREAD

**Issue by crioto** [subutai-io/control-center#913]
Determine proper tool tips for an items in main menu and implement them. Coordinate with @Almansherov on tool tips text. Make sure that they support i18n.

**Comment by Erkin97** [comment]
Inside of constructor of TrayControlWindow Class call setToolTip with QObject::tr(QString) for each QAction member

**Comment by Erkin97** [comment]
> Currently, Qt doesn't directly support tooltips being shown for QMenu objects
So to we need to reimplement some functions in QMenu

**Comment by Almansherov** [comment]
Need to cooperate with Scott and only after that to make ui/ux decisions. This issue is closed and if it will be needed, it will be re-opened.
