### ISSUE TITLE
Install Browser and E2E plugin (Firefox)

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#921]
Install e2e extension for Firefox

**Comment by ibragim13kz** [comment]
Done in Master.

**Comment by ibragim13kz** [comment]
Production, Win10. 
Couldn't install E2E for FireFox, restart of CC and FF didn't help. Also there is no ```extensions``` folder in FireFox root folder, so I think CC should create that folder.
![image](https://user-images.githubusercontent.com/33474101/43637207-2f3e257e-9736-11e8-8043-bbbc551adb0a.png)
[logs_15.txt](https://github.com/subutai-io/control-center/files/2256928/logs_15.txt)

**Comment by amangeldizhusubaliev** [comment]
fixed in dev.

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by Almansherov** [comment]
Successfully installed e2e plugin on Firefox:

![image](https://user-images.githubusercontent.com/32430693/47698042-ba04d600-dbdb-11e8-83e5-bc63bcfb2710.png)

Fixed on Prod
