### ISSUE TITLE
CC crashed

### ISSUE THREAD

**Issue by TerGunter** [subutai-io/control-center#943]
How to reproduce:
1. Open CC
2. Open SSH-Management
3. Generate several ssh-keys
4. Create env
5. Deploy ssh-key with the same env several time with several keys at one time

Result:
![image.png](https://images.zenhubusercontent.com/5ad825df4b5806bc2bcfb9d1/b86034cb-1686-4c5a-a12a-4dc5446d6c49)
[logs_17.txt](https://github.com/subutai-io/control-center/files/1983581/logs_17.txt)

**Comment by AlinaPenkina** [comment]
On ubuntu the same crash:
[logs_17.txt](https://github.com/subutai-io/control-center/files/1983598/logs_17.txt)

**Comment by amangeldizhusubaliev** [comment]
fixed on master.

**Comment by ibragim13kz** [comment]
Fixed in Prod.
