### ISSUE TITLE
Subutai Control Center has no version information on macOS

### ISSUE THREAD

**Issue by core-code** [subutai-io/control-center#944]
please add this to your Info.plist file to fix the missing version problem. 

	<key>CFBundleVersion</key>
	<string>6.10.0</string>
	<key> CFBundleShortVersionString </key>
	<string>6.10.0</string>

**Comment by core-code** [comment]
thanks.

i think you made some error though because you've added it between the LSUIElement KEY and VALUE, destroying the plist in the process. 

plists always have alternating keys and values...

**Comment by Erkin97** [comment]
@core-code thanks for your contribution, I changed plist. It will in production within this week

**Comment by TerGunter** [comment]
fixed on master
![image](https://user-images.githubusercontent.com/38347277/40113408-313a459a-592b-11e8-99e3-31d7c7700dae.png)

**Comment by amangeldizhusubaliev** [comment]
done
