### ISSUE TITLE
Debian 9  KDE support for CC deb package

### ISSUE THREAD

**Issue by liquuid** [subutai-io/control-center#946]
Installing the prod deb package of Subutai Control Center (prod version) give me the follow error on Debian 9 system:

```
Setting up subutai-control-center (7.0.0-0ubuntu1~trusty) ...
/var/lib/dpkg/info/subutai-control-center.postinst: line 47: desktop-file-install: command not found
Version: 7.0.0 Build: 7.0.0
```

When I tried run the binary received the following error:

```
 /opt/subutai/bin/subutai-control-center: error while loading shared libraries: libxcb-glx.so.0: cannot open shared object file: No such file or directory
```

I think this deb package need to be ported to Debian 9.

**Comment by Erkin97** [comment]
So, the problem is KDE does not support our method for installing .desktop file

**Comment by amangeldizhusubaliev** [comment]
fixed on master.

**Comment by amangeldizhusubaliev** [comment]
fixed on prod.
