### ISSUE TITLE
Improve requests to Bazaar

### ISSUE THREAD

**Issue by zubaidullo** [subutai-io/control-center#949]
Improve requests to Bazaar, now Control Center making so many requests to Bazaar, which can be optimized and decrease requests. 
If container states or other lifetime data needed we can create new REST endpoint with minimum data.

**Comment by ibragim13kz** [comment]
Not critical, but nice to have.

**Comment by Almansherov** [comment]
Discussion is closed due to the fact that it s not relevant anymore
