### ISSUE TITLE
Fix English in resource files

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/control-center#951]

**Comment by Erkin97** [comment]
* Resource files was updated. Need to make sure all texts are shown correct

**Comment by ibragim13kz** [comment]
Changes were not applied to: 
https://github.com/subutai-io/control-center/blob/master/commons/src/Logger.cpp 
https://github.com/subutai-io/control-center/blob/master/hub/src/NotificationObserver.cpp
https://github.com/subutai-io/control-center/blob/master/hub/src/SettingsManager.cpp - need to change `Info` to `Information` only.
https://github.com/subutai-io/control-center/blob/master/hub/src/SystemCallWrapper.cpp 

Not similar with a PR code: 
https://github.com/subutai-io/control-center/blob/master/hub/src/DlgGenerateSshKey.cpp - need to change `rights` to `privilegies`.

**Comment by ibragim13kz** [comment]
Didn't observe any wrong messages. Will reopen if needed.
