### ISSUE TITLE
P2P installation restart dialog should just be OK confirmation

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/control-center#953]
Shay clicked and the installation seemed to work but then it seemed to “ask” us this question in really bad English: “You installed P2P. Better to restart Control Center for correct work”. First this is not a question and second it is poor English that makes us look pretty unprofessional: I was embarrassed when Shay laughed. The following is needed instead:

See image in document #4 item: [problems](https://docs.google.com/document/d/1djfFGNofplc6aC6hcOlIRhx7cMD3btjqST4_GrDg4eU/edit#)

Instead of asking Yes/No, just show an “OK” confirmation dialog which restarts Control Center. No need to ask a question.
Use this text instead, “Control Center needs to restart for the P2P installation to complete.”

**Comment by akarasulu** [comment]
Remove this completely!!!!

**Comment by akarasulu** [comment]
Instead of showing a restart dialog. Tell the user, that it takes about 10-20 seconds for P2P to warm up connections. And make it an OK dialog box instead of this unnecessary restart.

**Comment by TerGunter** [comment]
fixed on master
![image](https://user-images.githubusercontent.com/38347277/40113343-f6819890-592a-11e8-96fc-d6a3a6dfcacc.png)

**Comment by amangeldizhusubaliev** [comment]
done
