### ISSUE TITLE
Start up CC after installation

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/control-center#954]
Users are not installing the software to just  leave after then. They want use their CC app there and then. We need to start CC after the install.

**Comment by amangeldizhusubaliev** [comment]
I still face this problem on master.

**Comment by Erkin97** [comment]
@amangeldizhusubaliev it was not fixed yet

**Comment by amangeldizhusubaliev** [comment]
Added launch CC commands to the postinstall scripts, which means there won't be "launch Control Center" option in installer - it will launch CC immediately after completing installation.

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by amangeldizhusubaliev** [comment]
We've removed this feature. Our solution - startup CC via vbs had it's own bad consequences. See #1548

**Comment by Almansherov** [comment]
Not relevant issue

**Comment by akarasulu** [comment]
What do you mean not a relevant issue? You mean that the setting to start CC on startup is working and this issue is no longer valid?

**Comment by Almansherov** [comment]
According to Amangeldi's comment, the fix of this issue leads to the problems with installation and update of components.
Comments are available here: #1548
