### ISSUE TITLE
Wrong error message during unregistration of peer.

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/control-center#971]
When user wants to unregister peer from bazaar, but on this peer envs are existing, CC should show proper error message

## Expected Behavior
Error message should be like: You can't unregister peer from bazaar, because there are envs.

## Current Behavior
It shows internal server error

![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/3e5c0045-f0cc-4155-86c0-bb3142e3e879)

**Comment by amangeldizhusubaliev** [comment]
fixed on master.

**Comment by ibragim13kz** [comment]
Failed in Prod.

**Comment by TerGunter** [comment]
Fixed on master
![screen shot 2018-05-26 at 12 30 26 pm](https://user-images.githubusercontent.com/38347277/40573276-ae7ae4e4-60e0-11e8-88eb-5037524abdb1.png)

**Comment by amangeldizhusubaliev** [comment]
Fixed on prod.
