### ISSUE TITLE
Chrome is installed but it's not recognised by control center

### ISSUE THREAD

**Issue by liquuid** [subutai-io/control-center#983]
The user Murilo Gatti report that issue, the Chrome is installed but control center can't find him

Picture of CC about panel:
https://files.slack.com/files-pri/T107M5C0G-FARQN7WMT/img_20180517_124031.jpg

Chrome version installed:  66.0.3359.181 64bits
Windows 10 1803-17134.1

Original thread message:
https://subutai-io.slack.com/archives/C107FJU94/p1526571711000445

**Comment by Erkin97** [comment]
It could be that your installation of google chrome is somehow messed up. You should check if this key is existing in your Windows Registry
```HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome```

**Comment by liquuid** [comment]
I'll ask the user to do this test.

**Comment by ibragim13kz** [comment]
Couldn't reproduce this issue. We'll reopen if it appears again.
